# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'char.ui'
#
# Created: Mon Jun  8 22:31:31 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 781)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout = QtGui.QFormLayout(self.groupBox)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.graphicsView = QtGui.QGraphicsView(self.groupBox)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.graphicsView)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox_3)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_3)
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_4 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_4)
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_9)
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_2.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_2.setWidget(11, QtGui.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_2.setWidget(12, QtGui.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_2.setWidget(13, QtGui.QFormLayout.LabelRole, self.label_13)
        self.label_14 = QtGui.QLabel(self.groupBox_3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_2.setWidget(14, QtGui.QFormLayout.LabelRole, self.label_14)
        self.lineEdit_5 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_5)
        self.lineEdit_6 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineEdit_6)
        self.lineEdit_7 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.FieldRole, self.lineEdit_7)
        self.lineEdit_8 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.formLayout_2.setWidget(9, QtGui.QFormLayout.FieldRole, self.lineEdit_8)
        self.lineEdit_9 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.FieldRole, self.lineEdit_9)
        self.lineEdit_10 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.formLayout_2.setWidget(10, QtGui.QFormLayout.FieldRole, self.lineEdit_10)
        self.lineEdit_11 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.formLayout_2.setWidget(11, QtGui.QFormLayout.FieldRole, self.lineEdit_11)
        self.lineEdit_12 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.formLayout_2.setWidget(12, QtGui.QFormLayout.FieldRole, self.lineEdit_12)
        self.lineEdit_13 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.formLayout_2.setWidget(13, QtGui.QFormLayout.FieldRole, self.lineEdit_13)
        self.plainTextEdit = QtGui.QPlainTextEdit(self.groupBox_3)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.formLayout_2.setWidget(14, QtGui.QFormLayout.FieldRole, self.plainTextEdit)
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_2)
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.groupBox_3)
        self.groupBox1 = QtGui.QGroupBox(self.groupBox)
        self.groupBox1.setObjectName(_fromUtf8("groupBox1"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox1)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QtGui.QPushButton(self.groupBox1)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.groupBox1)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.verticalLayout_4.addWidget(self.pushButton_2)
        self.groupbox = QtGui.QGroupBox(self.groupBox_2)
        self.groupbox.setObjectName(_fromUtf8("groupbox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupbox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_23 = QtGui.QLabel(self.groupbox)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_2.addWidget(self.label_23, 2, 4, 1, 1)
        self.label_24 = QtGui.QLabel(self.groupbox)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_2.addWidget(self.label_24, 2, 9, 1, 1)
        self.lineROBrainSwim = QtGui.QLineEdit(self.groupbox)
        self.lineROBrainSwim.setMinimumSize(QtCore.QSize(35, 22))
        self.lineROBrainSwim.setMaximumSize(QtCore.QSize(35, 22))
        self.lineROBrainSwim.setMaxLength(3)
        self.lineROBrainSwim.setReadOnly(True)
        self.lineROBrainSwim.setObjectName(_fromUtf8("lineROBrainSwim"))
        self.gridLayout_2.addWidget(self.lineROBrainSwim, 3, 6, 1, 1)
        self.label_25 = QtGui.QLabel(self.groupbox)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_2.addWidget(self.label_25, 2, 2, 1, 1)
        self.lineEditBrainTech = QtGui.QLineEdit(self.groupbox)
        self.lineEditBrainTech.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainTech.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainTech.setMaxLength(3)
        self.lineEditBrainTech.setObjectName(_fromUtf8("lineEditBrainTech"))
        self.gridLayout_2.addWidget(self.lineEditBrainTech, 1, 2, 1, 1)
        self.lineROBrainEnd = QtGui.QLineEdit(self.groupbox)
        self.lineROBrainEnd.setMinimumSize(QtCore.QSize(35, 22))
        self.lineROBrainEnd.setMaximumSize(QtCore.QSize(35, 22))
        self.lineROBrainEnd.setMaxLength(3)
        self.lineROBrainEnd.setReadOnly(True)
        self.lineROBrainEnd.setObjectName(_fromUtf8("lineROBrainEnd"))
        self.gridLayout_2.addWidget(self.lineROBrainEnd, 3, 3, 1, 1)
        self.lineROBrainStun = QtGui.QLineEdit(self.groupbox)
        self.lineROBrainStun.setMinimumSize(QtCore.QSize(35, 22))
        self.lineROBrainStun.setMaximumSize(QtCore.QSize(35, 22))
        self.lineROBrainStun.setMaxLength(3)
        self.lineROBrainStun.setReadOnly(True)
        self.lineROBrainStun.setObjectName(_fromUtf8("lineROBrainStun"))
        self.gridLayout_2.addWidget(self.lineROBrainStun, 3, 9, 1, 1)
        self.lineEditBrainInt = QtGui.QLineEdit(self.groupbox)
        self.lineEditBrainInt.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainInt.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainInt.setMaxLength(3)
        self.lineEditBrainInt.setObjectName(_fromUtf8("lineEditBrainInt"))
        self.gridLayout_2.addWidget(self.lineEditBrainInt, 1, 0, 1, 1)
        self.label_26 = QtGui.QLabel(self.groupbox)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_2.addWidget(self.label_26, 0, 3, 1, 1)
        self.label_27 = QtGui.QLabel(self.groupbox)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_2.addWidget(self.label_27, 2, 3, 1, 1)
        self.lineROBrainHum = QtGui.QLineEdit(self.groupbox)
        self.lineROBrainHum.setMinimumSize(QtCore.QSize(35, 22))
        self.lineROBrainHum.setMaximumSize(QtCore.QSize(35, 22))
        self.lineROBrainHum.setMaxLength(3)
        self.lineROBrainHum.setReadOnly(True)
        self.lineROBrainHum.setObjectName(_fromUtf8("lineROBrainHum"))
        self.gridLayout_2.addWidget(self.lineROBrainHum, 3, 1, 1, 1)
        self.lineROBrainRec = QtGui.QLineEdit(self.groupbox)
        self.lineROBrainRec.setMinimumSize(QtCore.QSize(35, 22))
        self.lineROBrainRec.setMaximumSize(QtCore.QSize(35, 22))
        self.lineROBrainRec.setMaxLength(3)
        self.lineROBrainRec.setReadOnly(True)
        self.lineROBrainRec.setObjectName(_fromUtf8("lineROBrainRec"))
        self.gridLayout_2.addWidget(self.lineROBrainRec, 3, 2, 1, 1)
        self.label_28 = QtGui.QLabel(self.groupbox)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_2.addWidget(self.label_28, 0, 4, 1, 1)
        self.lineEditBrainCool = QtGui.QLineEdit(self.groupbox)
        self.lineEditBrainCool.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainCool.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainCool.setMaxLength(3)
        self.lineEditBrainCool.setObjectName(_fromUtf8("lineEditBrainCool"))
        self.gridLayout_2.addWidget(self.lineEditBrainCool, 1, 4, 1, 1)
        self.label_29 = QtGui.QLabel(self.groupbox)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_2.addWidget(self.label_29, 2, 6, 1, 1)
        self.lineROBrainHits = QtGui.QLineEdit(self.groupbox)
        self.lineROBrainHits.setMinimumSize(QtCore.QSize(35, 22))
        self.lineROBrainHits.setMaximumSize(QtCore.QSize(35, 22))
        self.lineROBrainHits.setMaxLength(3)
        self.lineROBrainHits.setReadOnly(True)
        self.lineROBrainHits.setObjectName(_fromUtf8("lineROBrainHits"))
        self.gridLayout_2.addWidget(self.lineROBrainHits, 3, 8, 1, 1)
        self.lineEditBrainWill = QtGui.QLineEdit(self.groupbox)
        self.lineEditBrainWill.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainWill.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainWill.setMaxLength(3)
        self.lineEditBrainWill.setObjectName(_fromUtf8("lineEditBrainWill"))
        self.gridLayout_2.addWidget(self.lineEditBrainWill, 1, 5, 1, 1)
        self.lineEditBrainMove = QtGui.QLineEdit(self.groupbox)
        self.lineEditBrainMove.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainMove.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainMove.setMaxLength(3)
        self.lineEditBrainMove.setObjectName(_fromUtf8("lineEditBrainMove"))
        self.gridLayout_2.addWidget(self.lineEditBrainMove, 1, 8, 1, 1)
        self.lineEditBrainRef = QtGui.QLineEdit(self.groupbox)
        self.lineEditBrainRef.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainRef.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainRef.setMaxLength(3)
        self.lineEditBrainRef.setObjectName(_fromUtf8("lineEditBrainRef"))
        self.gridLayout_2.addWidget(self.lineEditBrainRef, 1, 1, 1, 1)
        self.label_30 = QtGui.QLabel(self.groupbox)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_2.addWidget(self.label_30, 0, 1, 1, 1)
        self.label_31 = QtGui.QLabel(self.groupbox)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_2.addWidget(self.label_31, 2, 1, 1, 1)
        self.label_32 = QtGui.QLabel(self.groupbox)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_2.addWidget(self.label_32, 0, 5, 1, 1)
        self.label_33 = QtGui.QLabel(self.groupbox)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_2.addWidget(self.label_33, 0, 2, 1, 1)
        self.lineEditBrainCon = QtGui.QLineEdit(self.groupbox)
        self.lineEditBrainCon.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainCon.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainCon.setMaxLength(3)
        self.lineEditBrainCon.setObjectName(_fromUtf8("lineEditBrainCon"))
        self.gridLayout_2.addWidget(self.lineEditBrainCon, 1, 7, 1, 1)
        self.label_34 = QtGui.QLabel(self.groupbox)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_2.addWidget(self.label_34, 0, 7, 1, 1)
        self.lineEditBrainBody = QtGui.QLineEdit(self.groupbox)
        self.lineEditBrainBody.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainBody.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainBody.setMaxLength(3)
        self.lineEditBrainBody.setObjectName(_fromUtf8("lineEditBrainBody"))
        self.gridLayout_2.addWidget(self.lineEditBrainBody, 1, 9, 1, 1)
        self.label_35 = QtGui.QLabel(self.groupbox)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_2.addWidget(self.label_35, 2, 0, 1, 1)
        self.lineEditBrainStr = QtGui.QLineEdit(self.groupbox)
        self.lineEditBrainStr.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainStr.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainStr.setMaxLength(3)
        self.lineEditBrainStr.setObjectName(_fromUtf8("lineEditBrainStr"))
        self.gridLayout_2.addWidget(self.lineEditBrainStr, 1, 6, 1, 1)
        self.label_36 = QtGui.QLabel(self.groupbox)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_2.addWidget(self.label_36, 0, 8, 1, 1)
        self.label_37 = QtGui.QLabel(self.groupbox)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_2.addWidget(self.label_37, 0, 6, 1, 1)
        self.lineROBrainSpr = QtGui.QLineEdit(self.groupbox)
        self.lineROBrainSpr.setMinimumSize(QtCore.QSize(35, 22))
        self.lineROBrainSpr.setMaximumSize(QtCore.QSize(35, 22))
        self.lineROBrainSpr.setMaxLength(3)
        self.lineROBrainSpr.setReadOnly(True)
        self.lineROBrainSpr.setObjectName(_fromUtf8("lineROBrainSpr"))
        self.gridLayout_2.addWidget(self.lineROBrainSpr, 3, 5, 1, 1)
        self.label_38 = QtGui.QLabel(self.groupbox)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_2.addWidget(self.label_38, 0, 9, 1, 1)
        self.lineROBrainLuck = QtGui.QLineEdit(self.groupbox)
        self.lineROBrainLuck.setMinimumSize(QtCore.QSize(35, 22))
        self.lineROBrainLuck.setMaximumSize(QtCore.QSize(35, 22))
        self.lineROBrainLuck.setMaxLength(3)
        self.lineROBrainLuck.setReadOnly(True)
        self.lineROBrainLuck.setObjectName(_fromUtf8("lineROBrainLuck"))
        self.gridLayout_2.addWidget(self.lineROBrainLuck, 3, 0, 1, 1)
        self.label_39 = QtGui.QLabel(self.groupbox)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_2.addWidget(self.label_39, 2, 5, 1, 1)
        self.label_40 = QtGui.QLabel(self.groupbox)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_2.addWidget(self.label_40, 0, 0, 1, 1)
        self.lineROBrainLeap = QtGui.QLineEdit(self.groupbox)
        self.lineROBrainLeap.setMinimumSize(QtCore.QSize(35, 22))
        self.lineROBrainLeap.setMaximumSize(QtCore.QSize(35, 22))
        self.lineROBrainLeap.setMaxLength(3)
        self.lineROBrainLeap.setReadOnly(True)
        self.lineROBrainLeap.setObjectName(_fromUtf8("lineROBrainLeap"))
        self.gridLayout_2.addWidget(self.lineROBrainLeap, 3, 7, 1, 1)
        self.lineEditBrainDex = QtGui.QLineEdit(self.groupbox)
        self.lineEditBrainDex.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainDex.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainDex.setMaxLength(3)
        self.lineEditBrainDex.setObjectName(_fromUtf8("lineEditBrainDex"))
        self.gridLayout_2.addWidget(self.lineEditBrainDex, 1, 3, 1, 1)
        self.label_41 = QtGui.QLabel(self.groupbox)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_2.addWidget(self.label_41, 2, 7, 1, 1)
        self.lineROBrainRun = QtGui.QLineEdit(self.groupbox)
        self.lineROBrainRun.setMinimumSize(QtCore.QSize(35, 22))
        self.lineROBrainRun.setMaximumSize(QtCore.QSize(35, 22))
        self.lineROBrainRun.setMaxLength(3)
        self.lineROBrainRun.setReadOnly(True)
        self.lineROBrainRun.setObjectName(_fromUtf8("lineROBrainRun"))
        self.gridLayout_2.addWidget(self.lineROBrainRun, 3, 4, 1, 1)
        self.label_42 = QtGui.QLabel(self.groupbox)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_2.addWidget(self.label_42, 2, 8, 1, 1)
        self.verticalLayout_4.addWidget(self.groupbox)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_15 = QtGui.QLabel(self.groupBox_4)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_15)
        self.label_16 = QtGui.QLabel(self.groupBox_4)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_16)
        self.comboBox = QtGui.QComboBox(self.groupBox_4)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.comboBox)
        self.comboBox_2 = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.comboBox_2)
        self.comboBox_3 = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.comboBox_3)
        self.comboBox_4 = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.comboBox_4)
        self.comboBox_5 = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.LabelRole, self.comboBox_5)
        self.comboBox_6 = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.LabelRole, self.comboBox_6)
        self.comboBoxSkills_2 = QtGui.QComboBox(self.groupBox_4)
        self.comboBoxSkills_2.setObjectName(_fromUtf8("comboBoxSkills_2"))
        self.formLayout_3.setWidget(7, QtGui.QFormLayout.LabelRole, self.comboBoxSkills_2)
        self.comboBox_8 = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_8.setObjectName(_fromUtf8("comboBox_8"))
        self.formLayout_3.setWidget(8, QtGui.QFormLayout.LabelRole, self.comboBox_8)
        self.comboBox_9 = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_9.setObjectName(_fromUtf8("comboBox_9"))
        self.formLayout_3.setWidget(9, QtGui.QFormLayout.LabelRole, self.comboBox_9)
        self.comboBox_10 = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_10.setObjectName(_fromUtf8("comboBox_10"))
        self.formLayout_3.setWidget(10, QtGui.QFormLayout.LabelRole, self.comboBox_10)
        self.comboBox_11 = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_11.setObjectName(_fromUtf8("comboBox_11"))
        self.formLayout_3.setWidget(11, QtGui.QFormLayout.LabelRole, self.comboBox_11)
        self.comboBox_12 = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_12.setObjectName(_fromUtf8("comboBox_12"))
        self.formLayout_3.setWidget(12, QtGui.QFormLayout.LabelRole, self.comboBox_12)
        self.comboBox_13 = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_13.setObjectName(_fromUtf8("comboBox_13"))
        self.formLayout_3.setWidget(13, QtGui.QFormLayout.LabelRole, self.comboBox_13)
        self.comboBox_14 = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_14.setObjectName(_fromUtf8("comboBox_14"))
        self.formLayout_3.setWidget(14, QtGui.QFormLayout.LabelRole, self.comboBox_14)
        self.comboBoxSkills = QtGui.QComboBox(self.groupBox_4)
        self.comboBoxSkills.setObjectName(_fromUtf8("comboBoxSkills"))
        self.formLayout_3.setWidget(15, QtGui.QFormLayout.LabelRole, self.comboBoxSkills)
        self.lineEditBrainKPOneLVL_15 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditBrainKPOneLVL_15.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_15.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_15.setMaxLength(3)
        self.lineEditBrainKPOneLVL_15.setObjectName(_fromUtf8("lineEditBrainKPOneLVL_15"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditBrainKPOneLVL_15)
        self.lineEditBrainKPOneLVL_16 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditBrainKPOneLVL_16.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_16.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_16.setMaxLength(3)
        self.lineEditBrainKPOneLVL_16.setObjectName(_fromUtf8("lineEditBrainKPOneLVL_16"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditBrainKPOneLVL_16)
        self.lineEditBrainKPOneLVL_17 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditBrainKPOneLVL_17.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_17.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_17.setMaxLength(3)
        self.lineEditBrainKPOneLVL_17.setObjectName(_fromUtf8("lineEditBrainKPOneLVL_17"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEditBrainKPOneLVL_17)
        self.lineEditBrainKPOneLVL_18 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditBrainKPOneLVL_18.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_18.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_18.setMaxLength(3)
        self.lineEditBrainKPOneLVL_18.setObjectName(_fromUtf8("lineEditBrainKPOneLVL_18"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEditBrainKPOneLVL_18)
        self.lineEditBrainKPOneLVL_19 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditBrainKPOneLVL_19.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_19.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_19.setMaxLength(3)
        self.lineEditBrainKPOneLVL_19.setObjectName(_fromUtf8("lineEditBrainKPOneLVL_19"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineEditBrainKPOneLVL_19)
        self.lineEditBrainKPOneLVL_20 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditBrainKPOneLVL_20.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_20.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_20.setMaxLength(3)
        self.lineEditBrainKPOneLVL_20.setObjectName(_fromUtf8("lineEditBrainKPOneLVL_20"))
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.FieldRole, self.lineEditBrainKPOneLVL_20)
        self.lineEditBrainKPOneLVL_21 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditBrainKPOneLVL_21.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_21.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_21.setMaxLength(3)
        self.lineEditBrainKPOneLVL_21.setObjectName(_fromUtf8("lineEditBrainKPOneLVL_21"))
        self.formLayout_3.setWidget(7, QtGui.QFormLayout.FieldRole, self.lineEditBrainKPOneLVL_21)
        self.lineEditBrainKPOneLVL_22 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditBrainKPOneLVL_22.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_22.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_22.setMaxLength(3)
        self.lineEditBrainKPOneLVL_22.setObjectName(_fromUtf8("lineEditBrainKPOneLVL_22"))
        self.formLayout_3.setWidget(8, QtGui.QFormLayout.FieldRole, self.lineEditBrainKPOneLVL_22)
        self.lineEditBrainKPOneLVL_23 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditBrainKPOneLVL_23.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_23.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_23.setMaxLength(3)
        self.lineEditBrainKPOneLVL_23.setObjectName(_fromUtf8("lineEditBrainKPOneLVL_23"))
        self.formLayout_3.setWidget(9, QtGui.QFormLayout.FieldRole, self.lineEditBrainKPOneLVL_23)
        self.lineEditBrainKPOneLVL_24 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditBrainKPOneLVL_24.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_24.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_24.setMaxLength(3)
        self.lineEditBrainKPOneLVL_24.setObjectName(_fromUtf8("lineEditBrainKPOneLVL_24"))
        self.formLayout_3.setWidget(10, QtGui.QFormLayout.FieldRole, self.lineEditBrainKPOneLVL_24)
        self.lineEditBrainKPOneLVL_25 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditBrainKPOneLVL_25.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_25.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_25.setMaxLength(3)
        self.lineEditBrainKPOneLVL_25.setObjectName(_fromUtf8("lineEditBrainKPOneLVL_25"))
        self.formLayout_3.setWidget(11, QtGui.QFormLayout.FieldRole, self.lineEditBrainKPOneLVL_25)
        self.lineEditBrainKPOneLVL_26 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditBrainKPOneLVL_26.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_26.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_26.setMaxLength(3)
        self.lineEditBrainKPOneLVL_26.setObjectName(_fromUtf8("lineEditBrainKPOneLVL_26"))
        self.formLayout_3.setWidget(12, QtGui.QFormLayout.FieldRole, self.lineEditBrainKPOneLVL_26)
        self.lineEditBrainKPOneLVL_27 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditBrainKPOneLVL_27.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_27.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_27.setMaxLength(3)
        self.lineEditBrainKPOneLVL_27.setObjectName(_fromUtf8("lineEditBrainKPOneLVL_27"))
        self.formLayout_3.setWidget(13, QtGui.QFormLayout.FieldRole, self.lineEditBrainKPOneLVL_27)
        self.lineEditBrainKPOneLVL_28 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditBrainKPOneLVL_28.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_28.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_28.setMaxLength(3)
        self.lineEditBrainKPOneLVL_28.setObjectName(_fromUtf8("lineEditBrainKPOneLVL_28"))
        self.formLayout_3.setWidget(14, QtGui.QFormLayout.FieldRole, self.lineEditBrainKPOneLVL_28)
        self.lineEditBrainKPOneLVL_29 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditBrainKPOneLVL_29.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_29.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_29.setMaxLength(3)
        self.lineEditBrainKPOneLVL_29.setObjectName(_fromUtf8("lineEditBrainKPOneLVL_29"))
        self.formLayout_3.setWidget(15, QtGui.QFormLayout.FieldRole, self.lineEditBrainKPOneLVL_29)
        self.comboBoxSkills_3 = QtGui.QComboBox(self.groupBox_4)
        self.comboBoxSkills_3.setObjectName(_fromUtf8("comboBoxSkills_3"))
        self.formLayout_3.setWidget(16, QtGui.QFormLayout.LabelRole, self.comboBoxSkills_3)
        self.lineEditBrainKPOneLVL_30 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditBrainKPOneLVL_30.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_30.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_30.setMaxLength(3)
        self.lineEditBrainKPOneLVL_30.setObjectName(_fromUtf8("lineEditBrainKPOneLVL_30"))
        self.formLayout_3.setWidget(16, QtGui.QFormLayout.FieldRole, self.lineEditBrainKPOneLVL_30)
        self.horizontalLayout_5.addLayout(self.formLayout_3)
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_17 = QtGui.QLabel(self.groupBox_4)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_17)
        self.label_18 = QtGui.QLabel(self.groupBox_4)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_18)
        self.comboBox_17 = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_17.setObjectName(_fromUtf8("comboBox_17"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.comboBox_17)
        self.lineEditBrainKPOneLVL = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditBrainKPOneLVL.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL.setMaxLength(3)
        self.lineEditBrainKPOneLVL.setObjectName(_fromUtf8("lineEditBrainKPOneLVL"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditBrainKPOneLVL)
        self.comboBox_18 = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_18.setObjectName(_fromUtf8("comboBox_18"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.comboBox_18)
        self.lineEditBrainKPTwoLVL = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditBrainKPTwoLVL.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPTwoLVL.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPTwoLVL.setMaxLength(3)
        self.lineEditBrainKPTwoLVL.setObjectName(_fromUtf8("lineEditBrainKPTwoLVL"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEditBrainKPTwoLVL)
        self.comboBox_19 = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_19.setObjectName(_fromUtf8("comboBox_19"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.LabelRole, self.comboBox_19)
        self.lineEditBrainKPOneLVL_2 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditBrainKPOneLVL_2.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_2.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_2.setMaxLength(3)
        self.lineEditBrainKPOneLVL_2.setObjectName(_fromUtf8("lineEditBrainKPOneLVL_2"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEditBrainKPOneLVL_2)
        self.comboBox_20 = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_20.setObjectName(_fromUtf8("comboBox_20"))
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.LabelRole, self.comboBox_20)
        self.lineEditBrainKPOneLVL_4 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditBrainKPOneLVL_4.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_4.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_4.setMaxLength(3)
        self.lineEditBrainKPOneLVL_4.setObjectName(_fromUtf8("lineEditBrainKPOneLVL_4"))
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineEditBrainKPOneLVL_4)
        self.comboBox_21 = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_21.setObjectName(_fromUtf8("comboBox_21"))
        self.formLayout_4.setWidget(6, QtGui.QFormLayout.LabelRole, self.comboBox_21)
        self.lineEditBrainKPOneLVL_5 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditBrainKPOneLVL_5.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_5.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_5.setMaxLength(3)
        self.lineEditBrainKPOneLVL_5.setObjectName(_fromUtf8("lineEditBrainKPOneLVL_5"))
        self.formLayout_4.setWidget(6, QtGui.QFormLayout.FieldRole, self.lineEditBrainKPOneLVL_5)
        self.comboBox_22 = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_22.setObjectName(_fromUtf8("comboBox_22"))
        self.formLayout_4.setWidget(7, QtGui.QFormLayout.LabelRole, self.comboBox_22)
        self.lineEditBrainKPOneLVL_6 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditBrainKPOneLVL_6.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_6.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_6.setMaxLength(3)
        self.lineEditBrainKPOneLVL_6.setObjectName(_fromUtf8("lineEditBrainKPOneLVL_6"))
        self.formLayout_4.setWidget(7, QtGui.QFormLayout.FieldRole, self.lineEditBrainKPOneLVL_6)
        self.comboBox_23 = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_23.setObjectName(_fromUtf8("comboBox_23"))
        self.formLayout_4.setWidget(8, QtGui.QFormLayout.LabelRole, self.comboBox_23)
        self.lineEditBrainKPOneLVL_7 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditBrainKPOneLVL_7.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_7.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_7.setMaxLength(3)
        self.lineEditBrainKPOneLVL_7.setObjectName(_fromUtf8("lineEditBrainKPOneLVL_7"))
        self.formLayout_4.setWidget(8, QtGui.QFormLayout.FieldRole, self.lineEditBrainKPOneLVL_7)
        self.comboBox_24 = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_24.setObjectName(_fromUtf8("comboBox_24"))
        self.formLayout_4.setWidget(9, QtGui.QFormLayout.LabelRole, self.comboBox_24)
        self.lineEditBrainKPOneLVL_8 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditBrainKPOneLVL_8.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_8.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_8.setMaxLength(3)
        self.lineEditBrainKPOneLVL_8.setObjectName(_fromUtf8("lineEditBrainKPOneLVL_8"))
        self.formLayout_4.setWidget(9, QtGui.QFormLayout.FieldRole, self.lineEditBrainKPOneLVL_8)
        self.comboBox_25 = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_25.setObjectName(_fromUtf8("comboBox_25"))
        self.formLayout_4.setWidget(10, QtGui.QFormLayout.LabelRole, self.comboBox_25)
        self.lineEditBrainKPOneLVL_9 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditBrainKPOneLVL_9.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_9.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_9.setMaxLength(3)
        self.lineEditBrainKPOneLVL_9.setObjectName(_fromUtf8("lineEditBrainKPOneLVL_9"))
        self.formLayout_4.setWidget(10, QtGui.QFormLayout.FieldRole, self.lineEditBrainKPOneLVL_9)
        self.comboBox_26 = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_26.setObjectName(_fromUtf8("comboBox_26"))
        self.formLayout_4.setWidget(11, QtGui.QFormLayout.LabelRole, self.comboBox_26)
        self.lineEditBrainKPOneLVL_10 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditBrainKPOneLVL_10.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_10.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_10.setMaxLength(3)
        self.lineEditBrainKPOneLVL_10.setObjectName(_fromUtf8("lineEditBrainKPOneLVL_10"))
        self.formLayout_4.setWidget(11, QtGui.QFormLayout.FieldRole, self.lineEditBrainKPOneLVL_10)
        self.comboBox_27 = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_27.setObjectName(_fromUtf8("comboBox_27"))
        self.formLayout_4.setWidget(12, QtGui.QFormLayout.LabelRole, self.comboBox_27)
        self.lineEditBrainKPOneLVL_11 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditBrainKPOneLVL_11.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_11.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_11.setMaxLength(3)
        self.lineEditBrainKPOneLVL_11.setObjectName(_fromUtf8("lineEditBrainKPOneLVL_11"))
        self.formLayout_4.setWidget(12, QtGui.QFormLayout.FieldRole, self.lineEditBrainKPOneLVL_11)
        self.comboBox_28 = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_28.setObjectName(_fromUtf8("comboBox_28"))
        self.formLayout_4.setWidget(13, QtGui.QFormLayout.LabelRole, self.comboBox_28)
        self.lineEditBrainKPOneLVL_12 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditBrainKPOneLVL_12.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_12.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_12.setMaxLength(3)
        self.lineEditBrainKPOneLVL_12.setObjectName(_fromUtf8("lineEditBrainKPOneLVL_12"))
        self.formLayout_4.setWidget(13, QtGui.QFormLayout.FieldRole, self.lineEditBrainKPOneLVL_12)
        self.comboBox_29 = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_29.setObjectName(_fromUtf8("comboBox_29"))
        self.formLayout_4.setWidget(14, QtGui.QFormLayout.LabelRole, self.comboBox_29)
        self.lineEditBrainKPOneLVL_13 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditBrainKPOneLVL_13.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_13.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_13.setMaxLength(3)
        self.lineEditBrainKPOneLVL_13.setObjectName(_fromUtf8("lineEditBrainKPOneLVL_13"))
        self.formLayout_4.setWidget(14, QtGui.QFormLayout.FieldRole, self.lineEditBrainKPOneLVL_13)
        self.comboBox_30 = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_30.setObjectName(_fromUtf8("comboBox_30"))
        self.formLayout_4.setWidget(15, QtGui.QFormLayout.LabelRole, self.comboBox_30)
        self.lineEditBrainKPOneLVL_14 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditBrainKPOneLVL_14.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_14.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_14.setMaxLength(3)
        self.lineEditBrainKPOneLVL_14.setObjectName(_fromUtf8("lineEditBrainKPOneLVL_14"))
        self.formLayout_4.setWidget(15, QtGui.QFormLayout.FieldRole, self.lineEditBrainKPOneLVL_14)
        self.comboBox_31 = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_31.setObjectName(_fromUtf8("comboBox_31"))
        self.formLayout_4.setWidget(16, QtGui.QFormLayout.LabelRole, self.comboBox_31)
        self.lineEditBrainKPOneLVL_31 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditBrainKPOneLVL_31.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_31.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL_31.setMaxLength(3)
        self.lineEditBrainKPOneLVL_31.setObjectName(_fromUtf8("lineEditBrainKPOneLVL_31"))
        self.formLayout_4.setWidget(16, QtGui.QFormLayout.FieldRole, self.lineEditBrainKPOneLVL_31)
        self.horizontalLayout_5.addLayout(self.formLayout_4)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.formLayout_5 = QtGui.QFormLayout(self.groupBox_5)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.lineEdit_14 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.lineEdit_14)
        self.lineEdit_15 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_15)
        self.lineEdit_16 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.lineEdit_16)
        self.lineEdit_17 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.lineEdit_17)
        self.lineEdit_18 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.LabelRole, self.lineEdit_18)
        self.lineEdit_19 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.formLayout_5.setWidget(5, QtGui.QFormLayout.LabelRole, self.lineEdit_19)
        self.lineEdit_20 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.formLayout_5.setWidget(6, QtGui.QFormLayout.LabelRole, self.lineEdit_20)
        self.lineEdit_21 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.formLayout_5.setWidget(7, QtGui.QFormLayout.LabelRole, self.lineEdit_21)
        self.lineEdit_22 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.formLayout_5.setWidget(8, QtGui.QFormLayout.LabelRole, self.lineEdit_22)
        self.lineEdit_23 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_23.setObjectName(_fromUtf8("lineEdit_23"))
        self.formLayout_5.setWidget(9, QtGui.QFormLayout.LabelRole, self.lineEdit_23)
        self.lineEdit_24 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_24.setObjectName(_fromUtf8("lineEdit_24"))
        self.formLayout_5.setWidget(10, QtGui.QFormLayout.LabelRole, self.lineEdit_24)
        self.lineEdit_25 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_25.setObjectName(_fromUtf8("lineEdit_25"))
        self.formLayout_5.setWidget(11, QtGui.QFormLayout.LabelRole, self.lineEdit_25)
        self.lineEdit_26 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_26.setObjectName(_fromUtf8("lineEdit_26"))
        self.formLayout_5.setWidget(12, QtGui.QFormLayout.LabelRole, self.lineEdit_26)
        self.lineEdit_27 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_27.setObjectName(_fromUtf8("lineEdit_27"))
        self.formLayout_5.setWidget(13, QtGui.QFormLayout.LabelRole, self.lineEdit_27)
        self.lineEdit_28 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_28.setObjectName(_fromUtf8("lineEdit_28"))
        self.formLayout_5.setWidget(14, QtGui.QFormLayout.LabelRole, self.lineEdit_28)
        self.lineEdit_29 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_29.setObjectName(_fromUtf8("lineEdit_29"))
        self.formLayout_5.setWidget(15, QtGui.QFormLayout.LabelRole, self.lineEdit_29)
        self.lineEdit_30 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_30.setObjectName(_fromUtf8("lineEdit_30"))
        self.formLayout_5.setWidget(16, QtGui.QFormLayout.LabelRole, self.lineEdit_30)
        self.lineEdit_31 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_31.setObjectName(_fromUtf8("lineEdit_31"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_31)
        self.lineEdit_32 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_32.setObjectName(_fromUtf8("lineEdit_32"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_32)
        self.lineEdit_33 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_33.setObjectName(_fromUtf8("lineEdit_33"))
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_33)
        self.lineEdit_34 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_34.setObjectName(_fromUtf8("lineEdit_34"))
        self.formLayout_5.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineEdit_34)
        self.lineEdit_35 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_35.setObjectName(_fromUtf8("lineEdit_35"))
        self.formLayout_5.setWidget(6, QtGui.QFormLayout.FieldRole, self.lineEdit_35)
        self.lineEdit_36 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_36.setObjectName(_fromUtf8("lineEdit_36"))
        self.formLayout_5.setWidget(7, QtGui.QFormLayout.FieldRole, self.lineEdit_36)
        self.lineEdit_37 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_37.setObjectName(_fromUtf8("lineEdit_37"))
        self.formLayout_5.setWidget(8, QtGui.QFormLayout.FieldRole, self.lineEdit_37)
        self.lineEdit_38 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_38.setObjectName(_fromUtf8("lineEdit_38"))
        self.formLayout_5.setWidget(9, QtGui.QFormLayout.FieldRole, self.lineEdit_38)
        self.lineEdit_39 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_39.setObjectName(_fromUtf8("lineEdit_39"))
        self.formLayout_5.setWidget(10, QtGui.QFormLayout.FieldRole, self.lineEdit_39)
        self.lineEdit_40 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_40.setObjectName(_fromUtf8("lineEdit_40"))
        self.formLayout_5.setWidget(11, QtGui.QFormLayout.FieldRole, self.lineEdit_40)
        self.lineEdit_41 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_41.setObjectName(_fromUtf8("lineEdit_41"))
        self.formLayout_5.setWidget(12, QtGui.QFormLayout.FieldRole, self.lineEdit_41)
        self.lineEdit_42 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_42.setObjectName(_fromUtf8("lineEdit_42"))
        self.formLayout_5.setWidget(13, QtGui.QFormLayout.FieldRole, self.lineEdit_42)
        self.lineEdit_43 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_43.setObjectName(_fromUtf8("lineEdit_43"))
        self.formLayout_5.setWidget(14, QtGui.QFormLayout.FieldRole, self.lineEdit_43)
        self.lineEdit_44 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_44.setObjectName(_fromUtf8("lineEdit_44"))
        self.formLayout_5.setWidget(15, QtGui.QFormLayout.FieldRole, self.lineEdit_44)
        self.lineEdit_45 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_45.setObjectName(_fromUtf8("lineEdit_45"))
        self.formLayout_5.setWidget(16, QtGui.QFormLayout.FieldRole, self.lineEdit_45)
        self.label = QtGui.QLabel(self.groupBox_5)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.label_19 = QtGui.QLabel(self.groupBox_5)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_19)
        self.verticalLayout_5.addWidget(self.groupBox_5)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lineEdit_118 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_118.setObjectName(_fromUtf8("lineEdit_118"))
        self.gridLayout.addWidget(self.lineEdit_118, 1, 1, 1, 1)
        self.lineEdit_121 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_121.setObjectName(_fromUtf8("lineEdit_121"))
        self.gridLayout.addWidget(self.lineEdit_121, 1, 4, 1, 1)
        self.lineEdit_98 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_98.setObjectName(_fromUtf8("lineEdit_98"))
        self.gridLayout.addWidget(self.lineEdit_98, 4, 8, 1, 1)
        self.lineEdit_75 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_75.setObjectName(_fromUtf8("lineEdit_75"))
        self.gridLayout.addWidget(self.lineEdit_75, 6, 3, 1, 1)
        self.lineEdit_58 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_58.setObjectName(_fromUtf8("lineEdit_58"))
        self.gridLayout.addWidget(self.lineEdit_58, 6, 1, 1, 1)
        self.lineEdit_46 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_46.setObjectName(_fromUtf8("lineEdit_46"))
        self.gridLayout.addWidget(self.lineEdit_46, 10, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.groupBox_6)
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout.addWidget(self.label_20, 0, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBox_6)
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout.addWidget(self.label_21, 0, 1, 1, 1)
        self.label_44 = QtGui.QLabel(self.groupBox_6)
        self.label_44.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout.addWidget(self.label_44, 0, 4, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBox_6)
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout.addWidget(self.label_22, 0, 2, 1, 1)
        self.lineEdit_51 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_51.setObjectName(_fromUtf8("lineEdit_51"))
        self.gridLayout.addWidget(self.lineEdit_51, 10, 5, 1, 1)
        self.lineEdit_52 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_52.setObjectName(_fromUtf8("lineEdit_52"))
        self.gridLayout.addWidget(self.lineEdit_52, 10, 6, 1, 1)
        self.lineEdit_80 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_80.setObjectName(_fromUtf8("lineEdit_80"))
        self.gridLayout.addWidget(self.lineEdit_80, 6, 8, 1, 1)
        self.lineEdit_87 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_87.setObjectName(_fromUtf8("lineEdit_87"))
        self.gridLayout.addWidget(self.lineEdit_87, 5, 6, 1, 1)
        self.lineEdit_68 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_68.setObjectName(_fromUtf8("lineEdit_68"))
        self.gridLayout.addWidget(self.lineEdit_68, 5, 0, 1, 1)
        self.lineEdit_70 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_70.setObjectName(_fromUtf8("lineEdit_70"))
        self.gridLayout.addWidget(self.lineEdit_70, 3, 0, 1, 1)
        self.lineEdit_69 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_69.setObjectName(_fromUtf8("lineEdit_69"))
        self.gridLayout.addWidget(self.lineEdit_69, 4, 0, 1, 1)
        self.lineEdit_71 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_71.setObjectName(_fromUtf8("lineEdit_71"))
        self.gridLayout.addWidget(self.lineEdit_71, 2, 0, 1, 1)
        self.lineEdit_81 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_81.setObjectName(_fromUtf8("lineEdit_81"))
        self.gridLayout.addWidget(self.lineEdit_81, 6, 9, 1, 1)
        self.lineEdit_84 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_84.setObjectName(_fromUtf8("lineEdit_84"))
        self.gridLayout.addWidget(self.lineEdit_84, 5, 3, 1, 1)
        self.lineEdit_82 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_82.setObjectName(_fromUtf8("lineEdit_82"))
        self.gridLayout.addWidget(self.lineEdit_82, 5, 1, 1, 1)
        self.lineEdit_83 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_83.setObjectName(_fromUtf8("lineEdit_83"))
        self.gridLayout.addWidget(self.lineEdit_83, 5, 2, 1, 1)
        self.lineEdit_86 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_86.setObjectName(_fromUtf8("lineEdit_86"))
        self.gridLayout.addWidget(self.lineEdit_86, 5, 5, 1, 1)
        self.lineEdit_89 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_89.setObjectName(_fromUtf8("lineEdit_89"))
        self.gridLayout.addWidget(self.lineEdit_89, 5, 8, 1, 1)
        self.lineEdit_85 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_85.setObjectName(_fromUtf8("lineEdit_85"))
        self.gridLayout.addWidget(self.lineEdit_85, 5, 4, 1, 1)
        self.lineEdit_88 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_88.setObjectName(_fromUtf8("lineEdit_88"))
        self.gridLayout.addWidget(self.lineEdit_88, 5, 7, 1, 1)
        self.lineEdit_91 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_91.setObjectName(_fromUtf8("lineEdit_91"))
        self.gridLayout.addWidget(self.lineEdit_91, 4, 1, 1, 1)
        self.lineEdit_90 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_90.setObjectName(_fromUtf8("lineEdit_90"))
        self.gridLayout.addWidget(self.lineEdit_90, 5, 9, 1, 1)
        self.lineEdit_95 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_95.setObjectName(_fromUtf8("lineEdit_95"))
        self.gridLayout.addWidget(self.lineEdit_95, 4, 5, 1, 1)
        self.lineEdit_92 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_92.setObjectName(_fromUtf8("lineEdit_92"))
        self.gridLayout.addWidget(self.lineEdit_92, 4, 2, 1, 1)
        self.lineEdit_94 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_94.setObjectName(_fromUtf8("lineEdit_94"))
        self.gridLayout.addWidget(self.lineEdit_94, 4, 4, 1, 1)
        self.lineEdit_93 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_93.setObjectName(_fromUtf8("lineEdit_93"))
        self.gridLayout.addWidget(self.lineEdit_93, 4, 3, 1, 1)
        self.lineEdit_96 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_96.setObjectName(_fromUtf8("lineEdit_96"))
        self.gridLayout.addWidget(self.lineEdit_96, 4, 6, 1, 1)
        self.lineEdit_97 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_97.setObjectName(_fromUtf8("lineEdit_97"))
        self.gridLayout.addWidget(self.lineEdit_97, 4, 7, 1, 1)
        self.lineEdit_99 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_99.setObjectName(_fromUtf8("lineEdit_99"))
        self.gridLayout.addWidget(self.lineEdit_99, 4, 9, 1, 1)
        self.lineEdit_110 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_110.setObjectName(_fromUtf8("lineEdit_110"))
        self.gridLayout.addWidget(self.lineEdit_110, 2, 2, 1, 1)
        self.lineEdit_105 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_105.setObjectName(_fromUtf8("lineEdit_105"))
        self.gridLayout.addWidget(self.lineEdit_105, 3, 6, 1, 1)
        self.lineEdit_104 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_104.setObjectName(_fromUtf8("lineEdit_104"))
        self.gridLayout.addWidget(self.lineEdit_104, 3, 5, 1, 1)
        self.lineEdit_103 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_103.setObjectName(_fromUtf8("lineEdit_103"))
        self.gridLayout.addWidget(self.lineEdit_103, 3, 4, 1, 1)
        self.lineEdit_100 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_100.setObjectName(_fromUtf8("lineEdit_100"))
        self.gridLayout.addWidget(self.lineEdit_100, 3, 1, 1, 1)
        self.lineEdit_101 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_101.setObjectName(_fromUtf8("lineEdit_101"))
        self.gridLayout.addWidget(self.lineEdit_101, 3, 2, 1, 1)
        self.lineEdit_106 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_106.setObjectName(_fromUtf8("lineEdit_106"))
        self.gridLayout.addWidget(self.lineEdit_106, 3, 7, 1, 1)
        self.lineEdit_102 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_102.setObjectName(_fromUtf8("lineEdit_102"))
        self.gridLayout.addWidget(self.lineEdit_102, 3, 3, 1, 1)
        self.lineEdit_108 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_108.setObjectName(_fromUtf8("lineEdit_108"))
        self.gridLayout.addWidget(self.lineEdit_108, 3, 9, 1, 1)
        self.lineEdit_107 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_107.setObjectName(_fromUtf8("lineEdit_107"))
        self.gridLayout.addWidget(self.lineEdit_107, 3, 8, 1, 1)
        self.lineEdit_114 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_114.setObjectName(_fromUtf8("lineEdit_114"))
        self.gridLayout.addWidget(self.lineEdit_114, 2, 6, 1, 1)
        self.lineEdit_111 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_111.setObjectName(_fromUtf8("lineEdit_111"))
        self.gridLayout.addWidget(self.lineEdit_111, 2, 3, 1, 1)
        self.lineEdit_109 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_109.setObjectName(_fromUtf8("lineEdit_109"))
        self.gridLayout.addWidget(self.lineEdit_109, 2, 1, 1, 1)
        self.lineEdit_113 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_113.setObjectName(_fromUtf8("lineEdit_113"))
        self.gridLayout.addWidget(self.lineEdit_113, 2, 5, 1, 1)
        self.lineEdit_112 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_112.setObjectName(_fromUtf8("lineEdit_112"))
        self.gridLayout.addWidget(self.lineEdit_112, 2, 4, 1, 1)
        self.lineEdit_117 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_117.setObjectName(_fromUtf8("lineEdit_117"))
        self.gridLayout.addWidget(self.lineEdit_117, 2, 9, 1, 1)
        self.lineEdit_115 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_115.setObjectName(_fromUtf8("lineEdit_115"))
        self.gridLayout.addWidget(self.lineEdit_115, 2, 7, 1, 1)
        self.lineEdit_123 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_123.setObjectName(_fromUtf8("lineEdit_123"))
        self.gridLayout.addWidget(self.lineEdit_123, 1, 6, 1, 1)
        self.lineEdit_116 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_116.setObjectName(_fromUtf8("lineEdit_116"))
        self.gridLayout.addWidget(self.lineEdit_116, 2, 8, 1, 1)
        self.lineEdit_119 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_119.setObjectName(_fromUtf8("lineEdit_119"))
        self.gridLayout.addWidget(self.lineEdit_119, 1, 3, 1, 1)
        self.lineEdit_122 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_122.setObjectName(_fromUtf8("lineEdit_122"))
        self.gridLayout.addWidget(self.lineEdit_122, 1, 5, 1, 1)
        self.lineEdit_120 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_120.setObjectName(_fromUtf8("lineEdit_120"))
        self.gridLayout.addWidget(self.lineEdit_120, 1, 2, 1, 1)
        self.lineEdit_124 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_124.setObjectName(_fromUtf8("lineEdit_124"))
        self.gridLayout.addWidget(self.lineEdit_124, 1, 7, 1, 1)
        self.lineEdit_126 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_126.setObjectName(_fromUtf8("lineEdit_126"))
        self.gridLayout.addWidget(self.lineEdit_126, 1, 9, 1, 1)
        self.lineEdit_67 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_67.setObjectName(_fromUtf8("lineEdit_67"))
        self.gridLayout.addWidget(self.lineEdit_67, 6, 0, 1, 1)
        self.lineEdit_72 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_72.setObjectName(_fromUtf8("lineEdit_72"))
        self.gridLayout.addWidget(self.lineEdit_72, 1, 0, 1, 1)
        self.lineEdit_74 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_74.setObjectName(_fromUtf8("lineEdit_74"))
        self.gridLayout.addWidget(self.lineEdit_74, 6, 2, 1, 1)
        self.lineEdit_77 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_77.setObjectName(_fromUtf8("lineEdit_77"))
        self.gridLayout.addWidget(self.lineEdit_77, 6, 5, 1, 1)
        self.lineEdit_79 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_79.setObjectName(_fromUtf8("lineEdit_79"))
        self.gridLayout.addWidget(self.lineEdit_79, 6, 7, 1, 1)
        self.lineEdit_125 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_125.setObjectName(_fromUtf8("lineEdit_125"))
        self.gridLayout.addWidget(self.lineEdit_125, 1, 8, 1, 1)
        self.label_43 = QtGui.QLabel(self.groupBox_6)
        self.label_43.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout.addWidget(self.label_43, 0, 3, 1, 1)
        self.label_45 = QtGui.QLabel(self.groupBox_6)
        self.label_45.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout.addWidget(self.label_45, 0, 5, 1, 1)
        self.label_46 = QtGui.QLabel(self.groupBox_6)
        self.label_46.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout.addWidget(self.label_46, 0, 6, 1, 1)
        self.label_47 = QtGui.QLabel(self.groupBox_6)
        self.label_47.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout.addWidget(self.label_47, 0, 7, 1, 1)
        self.label_48 = QtGui.QLabel(self.groupBox_6)
        self.label_48.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout.addWidget(self.label_48, 0, 8, 1, 1)
        self.lineEdit_47 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_47.setObjectName(_fromUtf8("lineEdit_47"))
        self.gridLayout.addWidget(self.lineEdit_47, 10, 1, 1, 1)
        self.lineEdit_59 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_59.setObjectName(_fromUtf8("lineEdit_59"))
        self.gridLayout.addWidget(self.lineEdit_59, 10, 8, 1, 1)
        self.lineEdit_55 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_55.setObjectName(_fromUtf8("lineEdit_55"))
        self.gridLayout.addWidget(self.lineEdit_55, 10, 9, 1, 1)
        self.lineEdit_53 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_53.setObjectName(_fromUtf8("lineEdit_53"))
        self.gridLayout.addWidget(self.lineEdit_53, 8, 7, 1, 1)
        self.lineEdit_56 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_56.setObjectName(_fromUtf8("lineEdit_56"))
        self.gridLayout.addWidget(self.lineEdit_56, 8, 9, 1, 1)
        self.label_49 = QtGui.QLabel(self.groupBox_6)
        self.label_49.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout.addWidget(self.label_49, 0, 9, 1, 1)
        self.lineEdit_61 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_61.setObjectName(_fromUtf8("lineEdit_61"))
        self.gridLayout.addWidget(self.lineEdit_61, 8, 5, 1, 1)
        self.lineEdit_63 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_63.setObjectName(_fromUtf8("lineEdit_63"))
        self.gridLayout.addWidget(self.lineEdit_63, 8, 3, 1, 1)
        self.lineEdit_64 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_64.setObjectName(_fromUtf8("lineEdit_64"))
        self.gridLayout.addWidget(self.lineEdit_64, 8, 2, 1, 1)
        self.lineEdit_65 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_65.setObjectName(_fromUtf8("lineEdit_65"))
        self.gridLayout.addWidget(self.lineEdit_65, 8, 1, 1, 1)
        self.lineEdit_76 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_76.setObjectName(_fromUtf8("lineEdit_76"))
        self.gridLayout.addWidget(self.lineEdit_76, 6, 4, 1, 1)
        self.lineEdit_78 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_78.setObjectName(_fromUtf8("lineEdit_78"))
        self.gridLayout.addWidget(self.lineEdit_78, 6, 6, 1, 1)
        self.lineEdit_66 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_66.setObjectName(_fromUtf8("lineEdit_66"))
        self.gridLayout.addWidget(self.lineEdit_66, 8, 0, 1, 1)
        self.lineEdit_48 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_48.setObjectName(_fromUtf8("lineEdit_48"))
        self.gridLayout.addWidget(self.lineEdit_48, 10, 2, 1, 1)
        self.lineEdit_50 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_50.setObjectName(_fromUtf8("lineEdit_50"))
        self.gridLayout.addWidget(self.lineEdit_50, 10, 4, 1, 1)
        self.lineEdit_49 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_49.setObjectName(_fromUtf8("lineEdit_49"))
        self.gridLayout.addWidget(self.lineEdit_49, 10, 3, 1, 1)
        self.lineEdit_57 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_57.setObjectName(_fromUtf8("lineEdit_57"))
        self.gridLayout.addWidget(self.lineEdit_57, 8, 8, 1, 1)
        self.lineEdit_62 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_62.setObjectName(_fromUtf8("lineEdit_62"))
        self.gridLayout.addWidget(self.lineEdit_62, 8, 4, 1, 1)
        self.lineEdit_54 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_54.setObjectName(_fromUtf8("lineEdit_54"))
        self.gridLayout.addWidget(self.lineEdit_54, 10, 7, 1, 1)
        self.lineEdit_60 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_60.setObjectName(_fromUtf8("lineEdit_60"))
        self.gridLayout.addWidget(self.lineEdit_60, 8, 6, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_6)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox", None))
        self.label_3.setText(_translate("MainWindow", "Lifepath:", None))
        self.label_5.setText(_translate("MainWindow", "Traits:", None))
        self.label_6.setText(_translate("MainWindow", "Feel About People:", None))
        self.label_7.setText(_translate("MainWindow", "You Value Most:", None))
        self.label_8.setText(_translate("MainWindow", "Valued Person:", None))
        self.label_9.setText(_translate("MainWindow", "Valued Possesion:", None))
        self.label_4.setText(_translate("MainWindow", "Clothes:", None))
        self.label_10.setText(_translate("MainWindow", "Hair:", None))
        self.label_11.setText(_translate("MainWindow", "Affectations:", None))
        self.label_12.setText(_translate("MainWindow", "Origins:", None))
        self.label_13.setText(_translate("MainWindow", "Languages:", None))
        self.label_14.setText(_translate("MainWindow", "Background:", None))
        self.label_2.setText(_translate("MainWindow", "Name:", None))
        self.pushButton.setText(_translate("MainWindow", "ChooseImage", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Character Information", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Stats", None))
        self.pushButton_2.setText(_translate("MainWindow", "Random Stats", None))
        self.label_23.setText(_translate("MainWindow", "Run", None))
        self.label_24.setText(_translate("MainWindow", "Stun", None))
        self.lineROBrainSwim.setText(_translate("MainWindow", "0", None))
        self.label_25.setText(_translate("MainWindow", "Rec", None))
        self.lineEditBrainTech.setText(_translate("MainWindow", "0", None))
        self.lineROBrainEnd.setText(_translate("MainWindow", "0", None))
        self.lineROBrainStun.setText(_translate("MainWindow", "0", None))
        self.lineEditBrainInt.setText(_translate("MainWindow", "0", None))
        self.label_26.setText(_translate("MainWindow", "Dex", None))
        self.label_27.setText(_translate("MainWindow", "End", None))
        self.lineROBrainHum.setText(_translate("MainWindow", "0", None))
        self.lineROBrainRec.setText(_translate("MainWindow", "0", None))
        self.label_28.setText(_translate("MainWindow", "Cool", None))
        self.lineEditBrainCool.setText(_translate("MainWindow", "0", None))
        self.label_29.setText(_translate("MainWindow", "Swim", None))
        self.lineROBrainHits.setText(_translate("MainWindow", "0", None))
        self.lineEditBrainWill.setText(_translate("MainWindow", "0", None))
        self.lineEditBrainMove.setText(_translate("MainWindow", "0", None))
        self.lineEditBrainRef.setText(_translate("MainWindow", "0", None))
        self.label_30.setText(_translate("MainWindow", "Ref", None))
        self.label_31.setText(_translate("MainWindow", "Hum", None))
        self.label_32.setText(_translate("MainWindow", "Will", None))
        self.label_33.setText(_translate("MainWindow", "Tech", None))
        self.lineEditBrainCon.setText(_translate("MainWindow", "0", None))
        self.label_34.setText(_translate("MainWindow", "Con", None))
        self.lineEditBrainBody.setText(_translate("MainWindow", "0", None))
        self.label_35.setText(_translate("MainWindow", "Luck", None))
        self.lineEditBrainStr.setText(_translate("MainWindow", "0", None))
        self.label_36.setText(_translate("MainWindow", "Move", None))
        self.label_37.setText(_translate("MainWindow", "Str", None))
        self.lineROBrainSpr.setText(_translate("MainWindow", "0", None))
        self.label_38.setText(_translate("MainWindow", "Body", None))
        self.lineROBrainLuck.setText(_translate("MainWindow", "0", None))
        self.label_39.setText(_translate("MainWindow", "Spr", None))
        self.label_40.setText(_translate("MainWindow", "Int", None))
        self.lineROBrainLeap.setText(_translate("MainWindow", "0", None))
        self.lineEditBrainDex.setText(_translate("MainWindow", "0", None))
        self.label_41.setText(_translate("MainWindow", "Leap", None))
        self.lineROBrainRun.setText(_translate("MainWindow", "0", None))
        self.label_42.setText(_translate("MainWindow", "Hits", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Skills and Perks", None))
        self.label_15.setText(_translate("MainWindow", "Key Skills", None))
        self.label_16.setText(_translate("MainWindow", "LVL", None))
        self.label_17.setText(_translate("MainWindow", "Key Perks / Talents", None))
        self.label_18.setText(_translate("MainWindow", "LVL", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Stats / Skills / Perks", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Outfit and Cybertech", None))
        self.label.setText(_translate("MainWindow", "Outfit & Core Cybertech", None))
        self.label_19.setText(_translate("MainWindow", "Location:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Outfit / Cybertech", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "GroupBox", None))
        self.label_20.setText(_translate("MainWindow", "Weapons or Attacks:", None))
        self.label_21.setText(_translate("MainWindow", "WA", None))
        self.label_44.setText(_translate("MainWindow", "DAMAGE", None))
        self.label_22.setText(_translate("MainWindow", "CON", None))
        self.label_43.setText(_translate("MainWindow", "AV", None))
        self.label_45.setText(_translate("MainWindow", "SHOTS", None))
        self.label_46.setText(_translate("MainWindow", "ROF", None))
        self.label_47.setText(_translate("MainWindow", "REL", None))
        self.label_48.setText(_translate("MainWindow", "RANGE", None))
        self.label_49.setText(_translate("MainWindow", "COST", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Weapons / Attacks", None))

