# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'meta_char_window.ui'
#
# Created: Sat Jul 18 01:32:59 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(594, 649)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEditName = QtGui.QLineEdit(self.groupBox)
        self.lineEditName.setObjectName(_fromUtf8("lineEditName"))
        self.horizontalLayout_3.addWidget(self.lineEditName)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.plainTextEditHistory = QtGui.QPlainTextEdit(self.groupBox)
        self.plainTextEditHistory.setObjectName(_fromUtf8("plainTextEditHistory"))
        self.horizontalLayout_4.addWidget(self.plainTextEditHistory)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addWidget(self.groupBox)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.formLayout_13 = QtGui.QFormLayout()
        self.formLayout_13.setObjectName(_fromUtf8("formLayout_13"))
        self.lineEditBrainName = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditBrainName.setObjectName(_fromUtf8("lineEditBrainName"))
        self.formLayout_13.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditBrainName)
        self.label_22 = QtGui.QLabel(self.groupBox_2)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.formLayout_13.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_22)
        self.verticalLayout_4.addLayout(self.formLayout_13)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_23 = QtGui.QLabel(self.groupBox_2)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_2.addWidget(self.label_23, 2, 4, 1, 1)
        self.label_24 = QtGui.QLabel(self.groupBox_2)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_2.addWidget(self.label_24, 2, 9, 1, 1)
        self.lineROBrainSwim = QtGui.QLineEdit(self.groupBox_2)
        self.lineROBrainSwim.setMinimumSize(QtCore.QSize(35, 22))
        self.lineROBrainSwim.setMaximumSize(QtCore.QSize(35, 22))
        self.lineROBrainSwim.setMaxLength(3)
        self.lineROBrainSwim.setReadOnly(True)
        self.lineROBrainSwim.setObjectName(_fromUtf8("lineROBrainSwim"))
        self.gridLayout_2.addWidget(self.lineROBrainSwim, 3, 6, 1, 1)
        self.label_25 = QtGui.QLabel(self.groupBox_2)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_2.addWidget(self.label_25, 2, 2, 1, 1)
        self.lineEditBrainTech = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditBrainTech.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainTech.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainTech.setMaxLength(3)
        self.lineEditBrainTech.setObjectName(_fromUtf8("lineEditBrainTech"))
        self.gridLayout_2.addWidget(self.lineEditBrainTech, 1, 2, 1, 1)
        self.lineROBrainEnd = QtGui.QLineEdit(self.groupBox_2)
        self.lineROBrainEnd.setMinimumSize(QtCore.QSize(35, 22))
        self.lineROBrainEnd.setMaximumSize(QtCore.QSize(35, 22))
        self.lineROBrainEnd.setMaxLength(3)
        self.lineROBrainEnd.setReadOnly(True)
        self.lineROBrainEnd.setObjectName(_fromUtf8("lineROBrainEnd"))
        self.gridLayout_2.addWidget(self.lineROBrainEnd, 3, 3, 1, 1)
        self.lineROBrainStun = QtGui.QLineEdit(self.groupBox_2)
        self.lineROBrainStun.setMinimumSize(QtCore.QSize(35, 22))
        self.lineROBrainStun.setMaximumSize(QtCore.QSize(35, 22))
        self.lineROBrainStun.setMaxLength(3)
        self.lineROBrainStun.setReadOnly(True)
        self.lineROBrainStun.setObjectName(_fromUtf8("lineROBrainStun"))
        self.gridLayout_2.addWidget(self.lineROBrainStun, 3, 9, 1, 1)
        self.lineEditBrainInt = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditBrainInt.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainInt.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainInt.setMaxLength(3)
        self.lineEditBrainInt.setObjectName(_fromUtf8("lineEditBrainInt"))
        self.gridLayout_2.addWidget(self.lineEditBrainInt, 1, 0, 1, 1)
        self.label_26 = QtGui.QLabel(self.groupBox_2)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_2.addWidget(self.label_26, 0, 3, 1, 1)
        self.label_27 = QtGui.QLabel(self.groupBox_2)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_2.addWidget(self.label_27, 2, 3, 1, 1)
        self.lineROBrainHum = QtGui.QLineEdit(self.groupBox_2)
        self.lineROBrainHum.setMinimumSize(QtCore.QSize(35, 22))
        self.lineROBrainHum.setMaximumSize(QtCore.QSize(35, 22))
        self.lineROBrainHum.setMaxLength(3)
        self.lineROBrainHum.setReadOnly(True)
        self.lineROBrainHum.setObjectName(_fromUtf8("lineROBrainHum"))
        self.gridLayout_2.addWidget(self.lineROBrainHum, 3, 1, 1, 1)
        self.lineROBrainRec = QtGui.QLineEdit(self.groupBox_2)
        self.lineROBrainRec.setMinimumSize(QtCore.QSize(35, 22))
        self.lineROBrainRec.setMaximumSize(QtCore.QSize(35, 22))
        self.lineROBrainRec.setMaxLength(3)
        self.lineROBrainRec.setReadOnly(True)
        self.lineROBrainRec.setObjectName(_fromUtf8("lineROBrainRec"))
        self.gridLayout_2.addWidget(self.lineROBrainRec, 3, 2, 1, 1)
        self.label_28 = QtGui.QLabel(self.groupBox_2)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_2.addWidget(self.label_28, 0, 4, 1, 1)
        self.lineEditBrainCool = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditBrainCool.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainCool.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainCool.setMaxLength(3)
        self.lineEditBrainCool.setObjectName(_fromUtf8("lineEditBrainCool"))
        self.gridLayout_2.addWidget(self.lineEditBrainCool, 1, 4, 1, 1)
        self.label_29 = QtGui.QLabel(self.groupBox_2)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_2.addWidget(self.label_29, 2, 6, 1, 1)
        self.lineROBrainHits = QtGui.QLineEdit(self.groupBox_2)
        self.lineROBrainHits.setMinimumSize(QtCore.QSize(35, 22))
        self.lineROBrainHits.setMaximumSize(QtCore.QSize(35, 22))
        self.lineROBrainHits.setMaxLength(3)
        self.lineROBrainHits.setReadOnly(True)
        self.lineROBrainHits.setObjectName(_fromUtf8("lineROBrainHits"))
        self.gridLayout_2.addWidget(self.lineROBrainHits, 3, 8, 1, 1)
        self.lineEditBrainWill = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditBrainWill.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainWill.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainWill.setMaxLength(3)
        self.lineEditBrainWill.setObjectName(_fromUtf8("lineEditBrainWill"))
        self.gridLayout_2.addWidget(self.lineEditBrainWill, 1, 5, 1, 1)
        self.lineEditBrainMove = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditBrainMove.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainMove.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainMove.setMaxLength(3)
        self.lineEditBrainMove.setObjectName(_fromUtf8("lineEditBrainMove"))
        self.gridLayout_2.addWidget(self.lineEditBrainMove, 1, 8, 1, 1)
        self.lineEditBrainRef = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditBrainRef.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainRef.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainRef.setMaxLength(3)
        self.lineEditBrainRef.setObjectName(_fromUtf8("lineEditBrainRef"))
        self.gridLayout_2.addWidget(self.lineEditBrainRef, 1, 1, 1, 1)
        self.label_30 = QtGui.QLabel(self.groupBox_2)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_2.addWidget(self.label_30, 0, 1, 1, 1)
        self.label_31 = QtGui.QLabel(self.groupBox_2)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_2.addWidget(self.label_31, 2, 1, 1, 1)
        self.label_32 = QtGui.QLabel(self.groupBox_2)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_2.addWidget(self.label_32, 0, 5, 1, 1)
        self.label_33 = QtGui.QLabel(self.groupBox_2)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_2.addWidget(self.label_33, 0, 2, 1, 1)
        self.lineEditBrainCon = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditBrainCon.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainCon.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainCon.setMaxLength(3)
        self.lineEditBrainCon.setObjectName(_fromUtf8("lineEditBrainCon"))
        self.gridLayout_2.addWidget(self.lineEditBrainCon, 1, 7, 1, 1)
        self.label_34 = QtGui.QLabel(self.groupBox_2)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_2.addWidget(self.label_34, 0, 7, 1, 1)
        self.lineEditBrainBody = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditBrainBody.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainBody.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainBody.setMaxLength(3)
        self.lineEditBrainBody.setObjectName(_fromUtf8("lineEditBrainBody"))
        self.gridLayout_2.addWidget(self.lineEditBrainBody, 1, 9, 1, 1)
        self.label_35 = QtGui.QLabel(self.groupBox_2)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_2.addWidget(self.label_35, 2, 0, 1, 1)
        self.lineEditBrainStr = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditBrainStr.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainStr.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainStr.setMaxLength(3)
        self.lineEditBrainStr.setObjectName(_fromUtf8("lineEditBrainStr"))
        self.gridLayout_2.addWidget(self.lineEditBrainStr, 1, 6, 1, 1)
        self.label_36 = QtGui.QLabel(self.groupBox_2)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_2.addWidget(self.label_36, 0, 8, 1, 1)
        self.label_37 = QtGui.QLabel(self.groupBox_2)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_2.addWidget(self.label_37, 0, 6, 1, 1)
        self.lineROBrainSpr = QtGui.QLineEdit(self.groupBox_2)
        self.lineROBrainSpr.setMinimumSize(QtCore.QSize(35, 22))
        self.lineROBrainSpr.setMaximumSize(QtCore.QSize(35, 22))
        self.lineROBrainSpr.setMaxLength(3)
        self.lineROBrainSpr.setReadOnly(True)
        self.lineROBrainSpr.setObjectName(_fromUtf8("lineROBrainSpr"))
        self.gridLayout_2.addWidget(self.lineROBrainSpr, 3, 5, 1, 1)
        self.label_38 = QtGui.QLabel(self.groupBox_2)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_2.addWidget(self.label_38, 0, 9, 1, 1)
        self.lineROBrainLuck = QtGui.QLineEdit(self.groupBox_2)
        self.lineROBrainLuck.setMinimumSize(QtCore.QSize(35, 22))
        self.lineROBrainLuck.setMaximumSize(QtCore.QSize(35, 22))
        self.lineROBrainLuck.setMaxLength(3)
        self.lineROBrainLuck.setReadOnly(True)
        self.lineROBrainLuck.setObjectName(_fromUtf8("lineROBrainLuck"))
        self.gridLayout_2.addWidget(self.lineROBrainLuck, 3, 0, 1, 1)
        self.label_39 = QtGui.QLabel(self.groupBox_2)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_2.addWidget(self.label_39, 2, 5, 1, 1)
        self.label_40 = QtGui.QLabel(self.groupBox_2)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_2.addWidget(self.label_40, 0, 0, 1, 1)
        self.lineROBrainLeap = QtGui.QLineEdit(self.groupBox_2)
        self.lineROBrainLeap.setMinimumSize(QtCore.QSize(35, 22))
        self.lineROBrainLeap.setMaximumSize(QtCore.QSize(35, 22))
        self.lineROBrainLeap.setMaxLength(3)
        self.lineROBrainLeap.setReadOnly(True)
        self.lineROBrainLeap.setObjectName(_fromUtf8("lineROBrainLeap"))
        self.gridLayout_2.addWidget(self.lineROBrainLeap, 3, 7, 1, 1)
        self.lineEditBrainDex = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditBrainDex.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainDex.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainDex.setMaxLength(3)
        self.lineEditBrainDex.setObjectName(_fromUtf8("lineEditBrainDex"))
        self.gridLayout_2.addWidget(self.lineEditBrainDex, 1, 3, 1, 1)
        self.label_41 = QtGui.QLabel(self.groupBox_2)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_2.addWidget(self.label_41, 2, 7, 1, 1)
        self.lineROBrainRun = QtGui.QLineEdit(self.groupBox_2)
        self.lineROBrainRun.setMinimumSize(QtCore.QSize(35, 22))
        self.lineROBrainRun.setMaximumSize(QtCore.QSize(35, 22))
        self.lineROBrainRun.setMaxLength(3)
        self.lineROBrainRun.setReadOnly(True)
        self.lineROBrainRun.setObjectName(_fromUtf8("lineROBrainRun"))
        self.gridLayout_2.addWidget(self.lineROBrainRun, 3, 4, 1, 1)
        self.label_42 = QtGui.QLabel(self.groupBox_2)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_2.addWidget(self.label_42, 2, 8, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_4)
        self.lineEditBrainKSOne = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditBrainKSOne.setObjectName(_fromUtf8("lineEditBrainKSOne"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lineEditBrainKSOne)
        self.lineEditBrainKSOneLVL = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditBrainKSOneLVL.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKSOneLVL.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKSOneLVL.setMaxLength(3)
        self.lineEditBrainKSOneLVL.setObjectName(_fromUtf8("lineEditBrainKSOneLVL"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditBrainKSOneLVL)
        self.lineEditBrainKSTwo = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditBrainKSTwo.setObjectName(_fromUtf8("lineEditBrainKSTwo"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lineEditBrainKSTwo)
        self.lineEditBrainKSTwoLVL = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditBrainKSTwoLVL.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKSTwoLVL.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKSTwoLVL.setMaxLength(3)
        self.lineEditBrainKSTwoLVL.setObjectName(_fromUtf8("lineEditBrainKSTwoLVL"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditBrainKSTwoLVL)
        self.horizontalLayout_5.addLayout(self.formLayout)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_6)
        self.lineEditBrainKPTwo = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditBrainKPTwo.setObjectName(_fromUtf8("lineEditBrainKPTwo"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.lineEditBrainKPTwo)
        self.lineEditBrainKPTwoLVL = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditBrainKPTwoLVL.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPTwoLVL.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPTwoLVL.setMaxLength(3)
        self.lineEditBrainKPTwoLVL.setObjectName(_fromUtf8("lineEditBrainKPTwoLVL"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEditBrainKPTwoLVL)
        self.lineEditBrainKPOne = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditBrainKPOne.setObjectName(_fromUtf8("lineEditBrainKPOne"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.lineEditBrainKPOne)
        self.lineEditBrainKPOneLVL = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditBrainKPOneLVL.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditBrainKPOneLVL.setMaxLength(3)
        self.lineEditBrainKPOneLVL.setObjectName(_fromUtf8("lineEditBrainKPOneLVL"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditBrainKPOneLVL)
        self.horizontalLayout_5.addLayout(self.formLayout_2)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.formLayout_3 = QtGui.QFormLayout(self.groupBox_4)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtGui.QLabel(self.groupBox_4)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_8)
        self.plainTextEditBrainGoals = QtGui.QPlainTextEdit(self.groupBox_4)
        self.plainTextEditBrainGoals.setObjectName(_fromUtf8("plainTextEditBrainGoals"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.plainTextEditBrainGoals)
        self.plainTextEditBrainLP = QtGui.QPlainTextEdit(self.groupBox_4)
        self.plainTextEditBrainLP.setObjectName(_fromUtf8("plainTextEditBrainLP"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.plainTextEditBrainLP)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.tab_3)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.formLayout_14 = QtGui.QFormLayout()
        self.formLayout_14.setObjectName(_fromUtf8("formLayout_14"))
        self.label_83 = QtGui.QLabel(self.groupBox_5)
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.formLayout_14.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_83)
        self.lineEditRHName = QtGui.QLineEdit(self.groupBox_5)
        self.lineEditRHName.setObjectName(_fromUtf8("lineEditRHName"))
        self.formLayout_14.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditRHName)
        self.verticalLayout_2.addLayout(self.formLayout_14)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_43 = QtGui.QLabel(self.groupBox_5)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_3.addWidget(self.label_43, 2, 4, 1, 1)
        self.label_44 = QtGui.QLabel(self.groupBox_5)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_3.addWidget(self.label_44, 2, 9, 1, 1)
        self.lineRORHSwim = QtGui.QLineEdit(self.groupBox_5)
        self.lineRORHSwim.setMinimumSize(QtCore.QSize(35, 22))
        self.lineRORHSwim.setMaximumSize(QtCore.QSize(35, 22))
        self.lineRORHSwim.setMaxLength(3)
        self.lineRORHSwim.setReadOnly(True)
        self.lineRORHSwim.setObjectName(_fromUtf8("lineRORHSwim"))
        self.gridLayout_3.addWidget(self.lineRORHSwim, 3, 6, 1, 1)
        self.label_45 = QtGui.QLabel(self.groupBox_5)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_3.addWidget(self.label_45, 2, 2, 1, 1)
        self.lineEditRHTech = QtGui.QLineEdit(self.groupBox_5)
        self.lineEditRHTech.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditRHTech.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditRHTech.setMaxLength(3)
        self.lineEditRHTech.setObjectName(_fromUtf8("lineEditRHTech"))
        self.gridLayout_3.addWidget(self.lineEditRHTech, 1, 2, 1, 1)
        self.lineRORHEnd = QtGui.QLineEdit(self.groupBox_5)
        self.lineRORHEnd.setMinimumSize(QtCore.QSize(35, 22))
        self.lineRORHEnd.setMaximumSize(QtCore.QSize(35, 22))
        self.lineRORHEnd.setMaxLength(3)
        self.lineRORHEnd.setReadOnly(True)
        self.lineRORHEnd.setObjectName(_fromUtf8("lineRORHEnd"))
        self.gridLayout_3.addWidget(self.lineRORHEnd, 3, 3, 1, 1)
        self.lineRORHStun = QtGui.QLineEdit(self.groupBox_5)
        self.lineRORHStun.setMinimumSize(QtCore.QSize(35, 22))
        self.lineRORHStun.setMaximumSize(QtCore.QSize(35, 22))
        self.lineRORHStun.setMaxLength(3)
        self.lineRORHStun.setReadOnly(True)
        self.lineRORHStun.setObjectName(_fromUtf8("lineRORHStun"))
        self.gridLayout_3.addWidget(self.lineRORHStun, 3, 9, 1, 1)
        self.lineEditRHInt = QtGui.QLineEdit(self.groupBox_5)
        self.lineEditRHInt.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditRHInt.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditRHInt.setMaxLength(3)
        self.lineEditRHInt.setObjectName(_fromUtf8("lineEditRHInt"))
        self.gridLayout_3.addWidget(self.lineEditRHInt, 1, 0, 1, 1)
        self.label_46 = QtGui.QLabel(self.groupBox_5)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_3.addWidget(self.label_46, 0, 3, 1, 1)
        self.label_47 = QtGui.QLabel(self.groupBox_5)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_3.addWidget(self.label_47, 2, 3, 1, 1)
        self.lineRORHHum = QtGui.QLineEdit(self.groupBox_5)
        self.lineRORHHum.setMinimumSize(QtCore.QSize(35, 22))
        self.lineRORHHum.setMaximumSize(QtCore.QSize(35, 22))
        self.lineRORHHum.setMaxLength(3)
        self.lineRORHHum.setReadOnly(True)
        self.lineRORHHum.setObjectName(_fromUtf8("lineRORHHum"))
        self.gridLayout_3.addWidget(self.lineRORHHum, 3, 1, 1, 1)
        self.lineRORHRec = QtGui.QLineEdit(self.groupBox_5)
        self.lineRORHRec.setMinimumSize(QtCore.QSize(35, 22))
        self.lineRORHRec.setMaximumSize(QtCore.QSize(35, 22))
        self.lineRORHRec.setMaxLength(3)
        self.lineRORHRec.setReadOnly(True)
        self.lineRORHRec.setObjectName(_fromUtf8("lineRORHRec"))
        self.gridLayout_3.addWidget(self.lineRORHRec, 3, 2, 1, 1)
        self.label_48 = QtGui.QLabel(self.groupBox_5)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_3.addWidget(self.label_48, 0, 4, 1, 1)
        self.lineEditRHCool = QtGui.QLineEdit(self.groupBox_5)
        self.lineEditRHCool.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditRHCool.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditRHCool.setMaxLength(3)
        self.lineEditRHCool.setObjectName(_fromUtf8("lineEditRHCool"))
        self.gridLayout_3.addWidget(self.lineEditRHCool, 1, 4, 1, 1)
        self.label_49 = QtGui.QLabel(self.groupBox_5)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_3.addWidget(self.label_49, 2, 6, 1, 1)
        self.lineRORHHits = QtGui.QLineEdit(self.groupBox_5)
        self.lineRORHHits.setMinimumSize(QtCore.QSize(35, 22))
        self.lineRORHHits.setMaximumSize(QtCore.QSize(35, 22))
        self.lineRORHHits.setMaxLength(3)
        self.lineRORHHits.setReadOnly(True)
        self.lineRORHHits.setObjectName(_fromUtf8("lineRORHHits"))
        self.gridLayout_3.addWidget(self.lineRORHHits, 3, 8, 1, 1)
        self.lineEditRHWill = QtGui.QLineEdit(self.groupBox_5)
        self.lineEditRHWill.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditRHWill.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditRHWill.setMaxLength(3)
        self.lineEditRHWill.setObjectName(_fromUtf8("lineEditRHWill"))
        self.gridLayout_3.addWidget(self.lineEditRHWill, 1, 5, 1, 1)
        self.lineEditRHMove = QtGui.QLineEdit(self.groupBox_5)
        self.lineEditRHMove.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditRHMove.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditRHMove.setMaxLength(3)
        self.lineEditRHMove.setObjectName(_fromUtf8("lineEditRHMove"))
        self.gridLayout_3.addWidget(self.lineEditRHMove, 1, 8, 1, 1)
        self.lineEditRHRef = QtGui.QLineEdit(self.groupBox_5)
        self.lineEditRHRef.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditRHRef.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditRHRef.setMaxLength(3)
        self.lineEditRHRef.setObjectName(_fromUtf8("lineEditRHRef"))
        self.gridLayout_3.addWidget(self.lineEditRHRef, 1, 1, 1, 1)
        self.label_50 = QtGui.QLabel(self.groupBox_5)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout_3.addWidget(self.label_50, 0, 1, 1, 1)
        self.label_51 = QtGui.QLabel(self.groupBox_5)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout_3.addWidget(self.label_51, 2, 1, 1, 1)
        self.label_52 = QtGui.QLabel(self.groupBox_5)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.gridLayout_3.addWidget(self.label_52, 0, 5, 1, 1)
        self.label_53 = QtGui.QLabel(self.groupBox_5)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.gridLayout_3.addWidget(self.label_53, 0, 2, 1, 1)
        self.lineEditRHCon = QtGui.QLineEdit(self.groupBox_5)
        self.lineEditRHCon.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditRHCon.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditRHCon.setMaxLength(3)
        self.lineEditRHCon.setObjectName(_fromUtf8("lineEditRHCon"))
        self.gridLayout_3.addWidget(self.lineEditRHCon, 1, 7, 1, 1)
        self.label_54 = QtGui.QLabel(self.groupBox_5)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.gridLayout_3.addWidget(self.label_54, 0, 7, 1, 1)
        self.lineEditRHBody = QtGui.QLineEdit(self.groupBox_5)
        self.lineEditRHBody.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditRHBody.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditRHBody.setMaxLength(3)
        self.lineEditRHBody.setObjectName(_fromUtf8("lineEditRHBody"))
        self.gridLayout_3.addWidget(self.lineEditRHBody, 1, 9, 1, 1)
        self.label_55 = QtGui.QLabel(self.groupBox_5)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.gridLayout_3.addWidget(self.label_55, 2, 0, 1, 1)
        self.lineEditRHStr = QtGui.QLineEdit(self.groupBox_5)
        self.lineEditRHStr.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditRHStr.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditRHStr.setMaxLength(3)
        self.lineEditRHStr.setObjectName(_fromUtf8("lineEditRHStr"))
        self.gridLayout_3.addWidget(self.lineEditRHStr, 1, 6, 1, 1)
        self.label_56 = QtGui.QLabel(self.groupBox_5)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.gridLayout_3.addWidget(self.label_56, 0, 8, 1, 1)
        self.label_57 = QtGui.QLabel(self.groupBox_5)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.gridLayout_3.addWidget(self.label_57, 0, 6, 1, 1)
        self.lineRORHSpr = QtGui.QLineEdit(self.groupBox_5)
        self.lineRORHSpr.setMinimumSize(QtCore.QSize(35, 22))
        self.lineRORHSpr.setMaximumSize(QtCore.QSize(35, 22))
        self.lineRORHSpr.setMaxLength(3)
        self.lineRORHSpr.setReadOnly(True)
        self.lineRORHSpr.setObjectName(_fromUtf8("lineRORHSpr"))
        self.gridLayout_3.addWidget(self.lineRORHSpr, 3, 5, 1, 1)
        self.label_58 = QtGui.QLabel(self.groupBox_5)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.gridLayout_3.addWidget(self.label_58, 0, 9, 1, 1)
        self.lineRORHLuck = QtGui.QLineEdit(self.groupBox_5)
        self.lineRORHLuck.setMinimumSize(QtCore.QSize(35, 22))
        self.lineRORHLuck.setMaximumSize(QtCore.QSize(35, 22))
        self.lineRORHLuck.setMaxLength(3)
        self.lineRORHLuck.setReadOnly(True)
        self.lineRORHLuck.setObjectName(_fromUtf8("lineRORHLuck"))
        self.gridLayout_3.addWidget(self.lineRORHLuck, 3, 0, 1, 1)
        self.label_59 = QtGui.QLabel(self.groupBox_5)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.gridLayout_3.addWidget(self.label_59, 2, 5, 1, 1)
        self.label_60 = QtGui.QLabel(self.groupBox_5)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.gridLayout_3.addWidget(self.label_60, 0, 0, 1, 1)
        self.lineRORHLeap = QtGui.QLineEdit(self.groupBox_5)
        self.lineRORHLeap.setMinimumSize(QtCore.QSize(35, 22))
        self.lineRORHLeap.setMaximumSize(QtCore.QSize(35, 22))
        self.lineRORHLeap.setMaxLength(3)
        self.lineRORHLeap.setReadOnly(True)
        self.lineRORHLeap.setObjectName(_fromUtf8("lineRORHLeap"))
        self.gridLayout_3.addWidget(self.lineRORHLeap, 3, 7, 1, 1)
        self.lineEditRHDex = QtGui.QLineEdit(self.groupBox_5)
        self.lineEditRHDex.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditRHDex.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditRHDex.setMaxLength(3)
        self.lineEditRHDex.setObjectName(_fromUtf8("lineEditRHDex"))
        self.gridLayout_3.addWidget(self.lineEditRHDex, 1, 3, 1, 1)
        self.label_61 = QtGui.QLabel(self.groupBox_5)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.gridLayout_3.addWidget(self.label_61, 2, 7, 1, 1)
        self.lineRORHRun = QtGui.QLineEdit(self.groupBox_5)
        self.lineRORHRun.setMinimumSize(QtCore.QSize(35, 22))
        self.lineRORHRun.setMaximumSize(QtCore.QSize(35, 22))
        self.lineRORHRun.setMaxLength(3)
        self.lineRORHRun.setReadOnly(True)
        self.lineRORHRun.setObjectName(_fromUtf8("lineRORHRun"))
        self.gridLayout_3.addWidget(self.lineRORHRun, 3, 4, 1, 1)
        self.label_62 = QtGui.QLabel(self.groupBox_5)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.gridLayout_3.addWidget(self.label_62, 2, 8, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_9 = QtGui.QLabel(self.groupBox_6)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtGui.QLabel(self.groupBox_6)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_10)
        self.lineEditRHKSOne = QtGui.QLineEdit(self.groupBox_6)
        self.lineEditRHKSOne.setObjectName(_fromUtf8("lineEditRHKSOne"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.lineEditRHKSOne)
        self.lineEditRHKSOneLVL = QtGui.QLineEdit(self.groupBox_6)
        self.lineEditRHKSOneLVL.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditRHKSOneLVL.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditRHKSOneLVL.setMaxLength(3)
        self.lineEditRHKSOneLVL.setObjectName(_fromUtf8("lineEditRHKSOneLVL"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditRHKSOneLVL)
        self.lineEditRHKSTwo = QtGui.QLineEdit(self.groupBox_6)
        self.lineEditRHKSTwo.setObjectName(_fromUtf8("lineEditRHKSTwo"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.lineEditRHKSTwo)
        self.lineEditRHKSTwoLVL = QtGui.QLineEdit(self.groupBox_6)
        self.lineEditRHKSTwoLVL.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditRHKSTwoLVL.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditRHKSTwoLVL.setMaxLength(3)
        self.lineEditRHKSTwoLVL.setObjectName(_fromUtf8("lineEditRHKSTwoLVL"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditRHKSTwoLVL)
        self.horizontalLayout_6.addLayout(self.formLayout_4)
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.label_11 = QtGui.QLabel(self.groupBox_6)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtGui.QLabel(self.groupBox_6)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_12)
        self.lineEditRHKPTwo = QtGui.QLineEdit(self.groupBox_6)
        self.lineEditRHKPTwo.setObjectName(_fromUtf8("lineEditRHKPTwo"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.lineEditRHKPTwo)
        self.lineEditRHKPTwoLVL = QtGui.QLineEdit(self.groupBox_6)
        self.lineEditRHKPTwoLVL.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditRHKPTwoLVL.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditRHKPTwoLVL.setMaxLength(3)
        self.lineEditRHKPTwoLVL.setObjectName(_fromUtf8("lineEditRHKPTwoLVL"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEditRHKPTwoLVL)
        self.lineEditRHKPOne = QtGui.QLineEdit(self.groupBox_6)
        self.lineEditRHKPOne.setObjectName(_fromUtf8("lineEditRHKPOne"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.lineEditRHKPOne)
        self.lineEditRHKPOneLVL = QtGui.QLineEdit(self.groupBox_6)
        self.lineEditRHKPOneLVL.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditRHKPOneLVL.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditRHKPOneLVL.setMaxLength(3)
        self.lineEditRHKPOneLVL.setObjectName(_fromUtf8("lineEditRHKPOneLVL"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditRHKPOneLVL)
        self.horizontalLayout_6.addLayout(self.formLayout_5)
        self.verticalLayout_2.addWidget(self.groupBox_6)
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.formLayout_6 = QtGui.QFormLayout(self.groupBox_7)
        self.formLayout_6.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.label_13 = QtGui.QLabel(self.groupBox_7)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_13)
        self.label_14 = QtGui.QLabel(self.groupBox_7)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_14)
        self.plainTextEditRHGoals = QtGui.QPlainTextEdit(self.groupBox_7)
        self.plainTextEditRHGoals.setObjectName(_fromUtf8("plainTextEditRHGoals"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.FieldRole, self.plainTextEditRHGoals)
        self.plainTextEditRHLP = QtGui.QPlainTextEdit(self.groupBox_7)
        self.plainTextEditRHLP.setObjectName(_fromUtf8("plainTextEditRHLP"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.plainTextEditRHLP)
        self.verticalLayout_2.addWidget(self.groupBox_7)
        self.horizontalLayout_7.addWidget(self.groupBox_5)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.tab_4)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.groupBox_8 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.formLayout_15 = QtGui.QFormLayout()
        self.formLayout_15.setObjectName(_fromUtf8("formLayout_15"))
        self.label_86 = QtGui.QLabel(self.groupBox_8)
        self.label_86.setObjectName(_fromUtf8("label_86"))
        self.formLayout_15.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_86)
        self.lineEditLHName = QtGui.QLineEdit(self.groupBox_8)
        self.lineEditLHName.setObjectName(_fromUtf8("lineEditLHName"))
        self.formLayout_15.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditLHName)
        self.verticalLayout_5.addLayout(self.formLayout_15)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_63 = QtGui.QLabel(self.groupBox_8)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.gridLayout_4.addWidget(self.label_63, 2, 4, 1, 1)
        self.label_64 = QtGui.QLabel(self.groupBox_8)
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.gridLayout_4.addWidget(self.label_64, 2, 9, 1, 1)
        self.lineROLHSwim = QtGui.QLineEdit(self.groupBox_8)
        self.lineROLHSwim.setMinimumSize(QtCore.QSize(35, 22))
        self.lineROLHSwim.setMaximumSize(QtCore.QSize(35, 22))
        self.lineROLHSwim.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineROLHSwim.setMaxLength(3)
        self.lineROLHSwim.setReadOnly(True)
        self.lineROLHSwim.setObjectName(_fromUtf8("lineROLHSwim"))
        self.gridLayout_4.addWidget(self.lineROLHSwim, 3, 6, 1, 1)
        self.label_65 = QtGui.QLabel(self.groupBox_8)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.gridLayout_4.addWidget(self.label_65, 2, 2, 1, 1)
        self.lineEditLHTech = QtGui.QLineEdit(self.groupBox_8)
        self.lineEditLHTech.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditLHTech.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditLHTech.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEditLHTech.setMaxLength(3)
        self.lineEditLHTech.setObjectName(_fromUtf8("lineEditLHTech"))
        self.gridLayout_4.addWidget(self.lineEditLHTech, 1, 2, 1, 1)
        self.lineROLHEnd = QtGui.QLineEdit(self.groupBox_8)
        self.lineROLHEnd.setMinimumSize(QtCore.QSize(35, 22))
        self.lineROLHEnd.setMaximumSize(QtCore.QSize(35, 22))
        self.lineROLHEnd.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineROLHEnd.setMaxLength(3)
        self.lineROLHEnd.setReadOnly(True)
        self.lineROLHEnd.setObjectName(_fromUtf8("lineROLHEnd"))
        self.gridLayout_4.addWidget(self.lineROLHEnd, 3, 3, 1, 1)
        self.lineROLHStun = QtGui.QLineEdit(self.groupBox_8)
        self.lineROLHStun.setMinimumSize(QtCore.QSize(35, 22))
        self.lineROLHStun.setMaximumSize(QtCore.QSize(35, 22))
        self.lineROLHStun.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineROLHStun.setMaxLength(3)
        self.lineROLHStun.setReadOnly(True)
        self.lineROLHStun.setObjectName(_fromUtf8("lineROLHStun"))
        self.gridLayout_4.addWidget(self.lineROLHStun, 3, 9, 1, 1)
        self.lineEditLHInt = QtGui.QLineEdit(self.groupBox_8)
        self.lineEditLHInt.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditLHInt.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditLHInt.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEditLHInt.setMaxLength(3)
        self.lineEditLHInt.setObjectName(_fromUtf8("lineEditLHInt"))
        self.gridLayout_4.addWidget(self.lineEditLHInt, 1, 0, 1, 1)
        self.label_66 = QtGui.QLabel(self.groupBox_8)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.gridLayout_4.addWidget(self.label_66, 0, 3, 1, 1)
        self.label_67 = QtGui.QLabel(self.groupBox_8)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.gridLayout_4.addWidget(self.label_67, 2, 3, 1, 1)
        self.lineROLHHum = QtGui.QLineEdit(self.groupBox_8)
        self.lineROLHHum.setMinimumSize(QtCore.QSize(35, 22))
        self.lineROLHHum.setMaximumSize(QtCore.QSize(35, 22))
        self.lineROLHHum.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineROLHHum.setMaxLength(3)
        self.lineROLHHum.setReadOnly(True)
        self.lineROLHHum.setObjectName(_fromUtf8("lineROLHHum"))
        self.gridLayout_4.addWidget(self.lineROLHHum, 3, 1, 1, 1)
        self.lineROLHRec = QtGui.QLineEdit(self.groupBox_8)
        self.lineROLHRec.setMinimumSize(QtCore.QSize(35, 22))
        self.lineROLHRec.setMaximumSize(QtCore.QSize(35, 22))
        self.lineROLHRec.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineROLHRec.setMaxLength(3)
        self.lineROLHRec.setReadOnly(True)
        self.lineROLHRec.setObjectName(_fromUtf8("lineROLHRec"))
        self.gridLayout_4.addWidget(self.lineROLHRec, 3, 2, 1, 1)
        self.label_68 = QtGui.QLabel(self.groupBox_8)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.gridLayout_4.addWidget(self.label_68, 0, 4, 1, 1)
        self.lineEditLHCool = QtGui.QLineEdit(self.groupBox_8)
        self.lineEditLHCool.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditLHCool.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditLHCool.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEditLHCool.setMaxLength(3)
        self.lineEditLHCool.setObjectName(_fromUtf8("lineEditLHCool"))
        self.gridLayout_4.addWidget(self.lineEditLHCool, 1, 4, 1, 1)
        self.label_69 = QtGui.QLabel(self.groupBox_8)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.gridLayout_4.addWidget(self.label_69, 2, 6, 1, 1)
        self.lineROLHHits = QtGui.QLineEdit(self.groupBox_8)
        self.lineROLHHits.setMinimumSize(QtCore.QSize(35, 22))
        self.lineROLHHits.setMaximumSize(QtCore.QSize(35, 22))
        self.lineROLHHits.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineROLHHits.setMaxLength(3)
        self.lineROLHHits.setReadOnly(True)
        self.lineROLHHits.setObjectName(_fromUtf8("lineROLHHits"))
        self.gridLayout_4.addWidget(self.lineROLHHits, 3, 8, 1, 1)
        self.lineEditLHWill = QtGui.QLineEdit(self.groupBox_8)
        self.lineEditLHWill.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditLHWill.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditLHWill.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEditLHWill.setMaxLength(3)
        self.lineEditLHWill.setObjectName(_fromUtf8("lineEditLHWill"))
        self.gridLayout_4.addWidget(self.lineEditLHWill, 1, 5, 1, 1)
        self.lineEditLHMove = QtGui.QLineEdit(self.groupBox_8)
        self.lineEditLHMove.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditLHMove.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditLHMove.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEditLHMove.setMaxLength(3)
        self.lineEditLHMove.setObjectName(_fromUtf8("lineEditLHMove"))
        self.gridLayout_4.addWidget(self.lineEditLHMove, 1, 8, 1, 1)
        self.lineEditLHRef = QtGui.QLineEdit(self.groupBox_8)
        self.lineEditLHRef.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditLHRef.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditLHRef.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEditLHRef.setMaxLength(3)
        self.lineEditLHRef.setObjectName(_fromUtf8("lineEditLHRef"))
        self.gridLayout_4.addWidget(self.lineEditLHRef, 1, 1, 1, 1)
        self.label_70 = QtGui.QLabel(self.groupBox_8)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.gridLayout_4.addWidget(self.label_70, 0, 1, 1, 1)
        self.label_71 = QtGui.QLabel(self.groupBox_8)
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.gridLayout_4.addWidget(self.label_71, 2, 1, 1, 1)
        self.label_72 = QtGui.QLabel(self.groupBox_8)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.gridLayout_4.addWidget(self.label_72, 0, 5, 1, 1)
        self.label_73 = QtGui.QLabel(self.groupBox_8)
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.gridLayout_4.addWidget(self.label_73, 0, 2, 1, 1)
        self.lineEditLHCon = QtGui.QLineEdit(self.groupBox_8)
        self.lineEditLHCon.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditLHCon.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditLHCon.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEditLHCon.setMaxLength(3)
        self.lineEditLHCon.setObjectName(_fromUtf8("lineEditLHCon"))
        self.gridLayout_4.addWidget(self.lineEditLHCon, 1, 7, 1, 1)
        self.label_74 = QtGui.QLabel(self.groupBox_8)
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.gridLayout_4.addWidget(self.label_74, 0, 7, 1, 1)
        self.lineEditLHBody = QtGui.QLineEdit(self.groupBox_8)
        self.lineEditLHBody.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditLHBody.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditLHBody.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEditLHBody.setMaxLength(3)
        self.lineEditLHBody.setObjectName(_fromUtf8("lineEditLHBody"))
        self.gridLayout_4.addWidget(self.lineEditLHBody, 1, 9, 1, 1)
        self.label_75 = QtGui.QLabel(self.groupBox_8)
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.gridLayout_4.addWidget(self.label_75, 2, 0, 1, 1)
        self.lineEditLHStr = QtGui.QLineEdit(self.groupBox_8)
        self.lineEditLHStr.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditLHStr.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditLHStr.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEditLHStr.setMaxLength(3)
        self.lineEditLHStr.setObjectName(_fromUtf8("lineEditLHStr"))
        self.gridLayout_4.addWidget(self.lineEditLHStr, 1, 6, 1, 1)
        self.label_76 = QtGui.QLabel(self.groupBox_8)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.gridLayout_4.addWidget(self.label_76, 0, 8, 1, 1)
        self.label_77 = QtGui.QLabel(self.groupBox_8)
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.gridLayout_4.addWidget(self.label_77, 0, 6, 1, 1)
        self.lineROLHSpr = QtGui.QLineEdit(self.groupBox_8)
        self.lineROLHSpr.setMinimumSize(QtCore.QSize(35, 22))
        self.lineROLHSpr.setMaximumSize(QtCore.QSize(35, 22))
        self.lineROLHSpr.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineROLHSpr.setMaxLength(3)
        self.lineROLHSpr.setReadOnly(True)
        self.lineROLHSpr.setObjectName(_fromUtf8("lineROLHSpr"))
        self.gridLayout_4.addWidget(self.lineROLHSpr, 3, 5, 1, 1)
        self.label_78 = QtGui.QLabel(self.groupBox_8)
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.gridLayout_4.addWidget(self.label_78, 0, 9, 1, 1)
        self.lineROLHLuck = QtGui.QLineEdit(self.groupBox_8)
        self.lineROLHLuck.setMinimumSize(QtCore.QSize(35, 22))
        self.lineROLHLuck.setMaximumSize(QtCore.QSize(35, 22))
        self.lineROLHLuck.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineROLHLuck.setMaxLength(3)
        self.lineROLHLuck.setReadOnly(True)
        self.lineROLHLuck.setObjectName(_fromUtf8("lineROLHLuck"))
        self.gridLayout_4.addWidget(self.lineROLHLuck, 3, 0, 1, 1)
        self.label_79 = QtGui.QLabel(self.groupBox_8)
        self.label_79.setObjectName(_fromUtf8("label_79"))
        self.gridLayout_4.addWidget(self.label_79, 2, 5, 1, 1)
        self.label_80 = QtGui.QLabel(self.groupBox_8)
        self.label_80.setObjectName(_fromUtf8("label_80"))
        self.gridLayout_4.addWidget(self.label_80, 0, 0, 1, 1)
        self.lineROLHLeap = QtGui.QLineEdit(self.groupBox_8)
        self.lineROLHLeap.setMinimumSize(QtCore.QSize(35, 22))
        self.lineROLHLeap.setMaximumSize(QtCore.QSize(35, 22))
        self.lineROLHLeap.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineROLHLeap.setMaxLength(3)
        self.lineROLHLeap.setReadOnly(True)
        self.lineROLHLeap.setObjectName(_fromUtf8("lineROLHLeap"))
        self.gridLayout_4.addWidget(self.lineROLHLeap, 3, 7, 1, 1)
        self.lineEditLHDex = QtGui.QLineEdit(self.groupBox_8)
        self.lineEditLHDex.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditLHDex.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditLHDex.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEditLHDex.setMaxLength(3)
        self.lineEditLHDex.setObjectName(_fromUtf8("lineEditLHDex"))
        self.gridLayout_4.addWidget(self.lineEditLHDex, 1, 3, 1, 1)
        self.label_81 = QtGui.QLabel(self.groupBox_8)
        self.label_81.setObjectName(_fromUtf8("label_81"))
        self.gridLayout_4.addWidget(self.label_81, 2, 7, 1, 1)
        self.lineROLHRun = QtGui.QLineEdit(self.groupBox_8)
        self.lineROLHRun.setMinimumSize(QtCore.QSize(35, 22))
        self.lineROLHRun.setMaximumSize(QtCore.QSize(35, 22))
        self.lineROLHRun.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineROLHRun.setMaxLength(3)
        self.lineROLHRun.setReadOnly(True)
        self.lineROLHRun.setObjectName(_fromUtf8("lineROLHRun"))
        self.gridLayout_4.addWidget(self.lineROLHRun, 3, 4, 1, 1)
        self.label_82 = QtGui.QLabel(self.groupBox_8)
        self.label_82.setObjectName(_fromUtf8("label_82"))
        self.gridLayout_4.addWidget(self.label_82, 2, 8, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_4)
        self.groupBox_9 = QtGui.QGroupBox(self.groupBox_8)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.formLayout_7 = QtGui.QFormLayout()
        self.formLayout_7.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.label_15 = QtGui.QLabel(self.groupBox_9)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_15)
        self.label_16 = QtGui.QLabel(self.groupBox_9)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_16)
        self.lineEditLHKSOne = QtGui.QLineEdit(self.groupBox_9)
        self.lineEditLHKSOne.setObjectName(_fromUtf8("lineEditLHKSOne"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.LabelRole, self.lineEditLHKSOne)
        self.lineEditLHKSOneLVL = QtGui.QLineEdit(self.groupBox_9)
        self.lineEditLHKSOneLVL.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditLHKSOneLVL.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditLHKSOneLVL.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEditLHKSOneLVL.setMaxLength(3)
        self.lineEditLHKSOneLVL.setObjectName(_fromUtf8("lineEditLHKSOneLVL"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditLHKSOneLVL)
        self.lineEditLHKSTwo = QtGui.QLineEdit(self.groupBox_9)
        self.lineEditLHKSTwo.setObjectName(_fromUtf8("lineEditLHKSTwo"))
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.LabelRole, self.lineEditLHKSTwo)
        self.lineEditLHKSTwoLVL = QtGui.QLineEdit(self.groupBox_9)
        self.lineEditLHKSTwoLVL.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditLHKSTwoLVL.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditLHKSTwoLVL.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEditLHKSTwoLVL.setMaxLength(3)
        self.lineEditLHKSTwoLVL.setObjectName(_fromUtf8("lineEditLHKSTwoLVL"))
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditLHKSTwoLVL)
        self.horizontalLayout_8.addLayout(self.formLayout_7)
        self.formLayout_8 = QtGui.QFormLayout()
        self.formLayout_8.setObjectName(_fromUtf8("formLayout_8"))
        self.label_17 = QtGui.QLabel(self.groupBox_9)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_17)
        self.label_18 = QtGui.QLabel(self.groupBox_9)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_18)
        self.lineEditLHKPTwo = QtGui.QLineEdit(self.groupBox_9)
        self.lineEditLHKPTwo.setObjectName(_fromUtf8("lineEditLHKPTwo"))
        self.formLayout_8.setWidget(3, QtGui.QFormLayout.LabelRole, self.lineEditLHKPTwo)
        self.lineEditLHKPTwoLVL = QtGui.QLineEdit(self.groupBox_9)
        self.lineEditLHKPTwoLVL.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditLHKPTwoLVL.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditLHKPTwoLVL.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEditLHKPTwoLVL.setMaxLength(3)
        self.lineEditLHKPTwoLVL.setObjectName(_fromUtf8("lineEditLHKPTwoLVL"))
        self.formLayout_8.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEditLHKPTwoLVL)
        self.lineEditLHKPOne = QtGui.QLineEdit(self.groupBox_9)
        self.lineEditLHKPOne.setObjectName(_fromUtf8("lineEditLHKPOne"))
        self.formLayout_8.setWidget(2, QtGui.QFormLayout.LabelRole, self.lineEditLHKPOne)
        self.lineEditLHKPOneLVL = QtGui.QLineEdit(self.groupBox_9)
        self.lineEditLHKPOneLVL.setMinimumSize(QtCore.QSize(35, 22))
        self.lineEditLHKPOneLVL.setMaximumSize(QtCore.QSize(35, 22))
        self.lineEditLHKPOneLVL.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEditLHKPOneLVL.setMaxLength(3)
        self.lineEditLHKPOneLVL.setObjectName(_fromUtf8("lineEditLHKPOneLVL"))
        self.formLayout_8.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditLHKPOneLVL)
        self.horizontalLayout_8.addLayout(self.formLayout_8)
        self.verticalLayout_5.addWidget(self.groupBox_9)
        self.groupBox_10 = QtGui.QGroupBox(self.groupBox_8)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.formLayout_9 = QtGui.QFormLayout(self.groupBox_10)
        self.formLayout_9.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_9.setObjectName(_fromUtf8("formLayout_9"))
        self.label_19 = QtGui.QLabel(self.groupBox_10)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_9.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_19)
        self.label_20 = QtGui.QLabel(self.groupBox_10)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.formLayout_9.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_20)
        self.plainTextEditLHGoals = QtGui.QPlainTextEdit(self.groupBox_10)
        self.plainTextEditLHGoals.setObjectName(_fromUtf8("plainTextEditLHGoals"))
        self.formLayout_9.setWidget(1, QtGui.QFormLayout.FieldRole, self.plainTextEditLHGoals)
        self.plainTextEditLHLP = QtGui.QPlainTextEdit(self.groupBox_10)
        self.plainTextEditLHLP.setObjectName(_fromUtf8("plainTextEditLHLP"))
        self.formLayout_9.setWidget(0, QtGui.QFormLayout.FieldRole, self.plainTextEditLHLP)
        self.verticalLayout_5.addWidget(self.groupBox_10)
        self.horizontalLayout_9.addWidget(self.groupBox_8)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.groupBox_11 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.formLayout_10 = QtGui.QFormLayout(self.groupBox_11)
        self.formLayout_10.setObjectName(_fromUtf8("formLayout_10"))
        self.label_21 = QtGui.QLabel(self.groupBox_11)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.formLayout_10.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_21)
        self.label_84 = QtGui.QLabel(self.groupBox_11)
        self.label_84.setObjectName(_fromUtf8("label_84"))
        self.formLayout_10.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_84)
        self.label_85 = QtGui.QLabel(self.groupBox_11)
        self.label_85.setObjectName(_fromUtf8("label_85"))
        self.formLayout_10.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_85)
        self.lineEditBodyLeaders = QtGui.QLineEdit(self.groupBox_11)
        self.lineEditBodyLeaders.setObjectName(_fromUtf8("lineEditBodyLeaders"))
        self.formLayout_10.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditBodyLeaders)
        self.lineEditBodySoldiers = QtGui.QLineEdit(self.groupBox_11)
        self.lineEditBodySoldiers.setObjectName(_fromUtf8("lineEditBodySoldiers"))
        self.formLayout_10.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditBodySoldiers)
        self.lineEditBodyGrunts = QtGui.QLineEdit(self.groupBox_11)
        self.lineEditBodyGrunts.setObjectName(_fromUtf8("lineEditBodyGrunts"))
        self.formLayout_10.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditBodyGrunts)
        self.verticalLayout_6.addWidget(self.groupBox_11)
        self.groupBox_12 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.formLayout_11 = QtGui.QFormLayout(self.groupBox_12)
        self.formLayout_11.setObjectName(_fromUtf8("formLayout_11"))
        self.plainTextEditBodyAssets = QtGui.QPlainTextEdit(self.groupBox_12)
        self.plainTextEditBodyAssets.setObjectName(_fromUtf8("plainTextEditBodyAssets"))
        self.formLayout_11.setWidget(0, QtGui.QFormLayout.FieldRole, self.plainTextEditBodyAssets)
        self.verticalLayout_6.addWidget(self.groupBox_12)
        self.groupBox_13 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.formLayout_12 = QtGui.QFormLayout(self.groupBox_13)
        self.formLayout_12.setObjectName(_fromUtf8("formLayout_12"))
        self.plainTextEditBodyVehicles = QtGui.QPlainTextEdit(self.groupBox_13)
        self.plainTextEditBodyVehicles.setObjectName(_fromUtf8("plainTextEditBodyVehicles"))
        self.formLayout_12.setWidget(0, QtGui.QFormLayout.FieldRole, self.plainTextEditBodyVehicles)
        self.verticalLayout_6.addWidget(self.groupBox_13)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 594, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MetaChar Creator", None))
        self.groupBox.setTitle(_translate("MainWindow", "Meta Char", None))
        self.label.setText(_translate("MainWindow", "Name:", None))
        self.label_2.setText(_translate("MainWindow", "History:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Main", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Stats", None))
        self.label_22.setText(_translate("MainWindow", "Name:", None))
        self.label_23.setText(_translate("MainWindow", "Run", None))
        self.label_24.setText(_translate("MainWindow", "Stun", None))
        self.lineROBrainSwim.setText(_translate("MainWindow", "0", None))
        self.label_25.setText(_translate("MainWindow", "Rec", None))
        self.lineEditBrainTech.setText(_translate("MainWindow", "0", None))
        self.lineROBrainEnd.setText(_translate("MainWindow", "0", None))
        self.lineROBrainStun.setText(_translate("MainWindow", "0", None))
        self.lineEditBrainInt.setText(_translate("MainWindow", "0", None))
        self.label_26.setText(_translate("MainWindow", "Dex", None))
        self.label_27.setText(_translate("MainWindow", "End", None))
        self.lineROBrainHum.setText(_translate("MainWindow", "0", None))
        self.lineROBrainRec.setText(_translate("MainWindow", "0", None))
        self.label_28.setText(_translate("MainWindow", "Cool", None))
        self.lineEditBrainCool.setText(_translate("MainWindow", "0", None))
        self.label_29.setText(_translate("MainWindow", "Swim", None))
        self.lineROBrainHits.setText(_translate("MainWindow", "0", None))
        self.lineEditBrainWill.setText(_translate("MainWindow", "0", None))
        self.lineEditBrainMove.setText(_translate("MainWindow", "0", None))
        self.lineEditBrainRef.setText(_translate("MainWindow", "0", None))
        self.label_30.setText(_translate("MainWindow", "Ref", None))
        self.label_31.setText(_translate("MainWindow", "Hum", None))
        self.label_32.setText(_translate("MainWindow", "Will", None))
        self.label_33.setText(_translate("MainWindow", "Tech", None))
        self.lineEditBrainCon.setText(_translate("MainWindow", "0", None))
        self.label_34.setText(_translate("MainWindow", "Con", None))
        self.lineEditBrainBody.setText(_translate("MainWindow", "0", None))
        self.label_35.setText(_translate("MainWindow", "Luck", None))
        self.lineEditBrainStr.setText(_translate("MainWindow", "0", None))
        self.label_36.setText(_translate("MainWindow", "Move", None))
        self.label_37.setText(_translate("MainWindow", "Str", None))
        self.lineROBrainSpr.setText(_translate("MainWindow", "0", None))
        self.label_38.setText(_translate("MainWindow", "Body", None))
        self.lineROBrainLuck.setText(_translate("MainWindow", "0", None))
        self.label_39.setText(_translate("MainWindow", "Spr", None))
        self.label_40.setText(_translate("MainWindow", "Int", None))
        self.lineROBrainLeap.setText(_translate("MainWindow", "0", None))
        self.lineEditBrainDex.setText(_translate("MainWindow", "0", None))
        self.label_41.setText(_translate("MainWindow", "Leap", None))
        self.lineROBrainRun.setText(_translate("MainWindow", "0", None))
        self.label_42.setText(_translate("MainWindow", "Hits", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Key Skills", None))
        self.label_3.setText(_translate("MainWindow", "Key Skills", None))
        self.label_4.setText(_translate("MainWindow", "LVL", None))
        self.label_5.setText(_translate("MainWindow", "Key Perks / Talents", None))
        self.label_6.setText(_translate("MainWindow", "LVL", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "GroupBox", None))
        self.label_7.setText(_translate("MainWindow", "Life Path:", None))
        self.label_8.setText(_translate("MainWindow", "Goals:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Brain", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Stats", None))
        self.label_83.setText(_translate("MainWindow", "Name:", None))
        self.label_43.setText(_translate("MainWindow", "Run", None))
        self.label_44.setText(_translate("MainWindow", "Stun", None))
        self.lineRORHSwim.setText(_translate("MainWindow", "0", None))
        self.label_45.setText(_translate("MainWindow", "Rec", None))
        self.lineEditRHTech.setText(_translate("MainWindow", "0", None))
        self.lineRORHEnd.setText(_translate("MainWindow", "0", None))
        self.lineRORHStun.setText(_translate("MainWindow", "0", None))
        self.lineEditRHInt.setText(_translate("MainWindow", "0", None))
        self.label_46.setText(_translate("MainWindow", "Dex", None))
        self.label_47.setText(_translate("MainWindow", "End", None))
        self.lineRORHHum.setText(_translate("MainWindow", "0", None))
        self.lineRORHRec.setText(_translate("MainWindow", "0", None))
        self.label_48.setText(_translate("MainWindow", "Cool", None))
        self.lineEditRHCool.setText(_translate("MainWindow", "0", None))
        self.label_49.setText(_translate("MainWindow", "Swim", None))
        self.lineRORHHits.setText(_translate("MainWindow", "0", None))
        self.lineEditRHWill.setText(_translate("MainWindow", "0", None))
        self.lineEditRHMove.setText(_translate("MainWindow", "0", None))
        self.lineEditRHRef.setText(_translate("MainWindow", "0", None))
        self.label_50.setText(_translate("MainWindow", "Ref", None))
        self.label_51.setText(_translate("MainWindow", "Hum", None))
        self.label_52.setText(_translate("MainWindow", "Will", None))
        self.label_53.setText(_translate("MainWindow", "Tech", None))
        self.lineEditRHCon.setText(_translate("MainWindow", "0", None))
        self.label_54.setText(_translate("MainWindow", "Con", None))
        self.lineEditRHBody.setText(_translate("MainWindow", "0", None))
        self.label_55.setText(_translate("MainWindow", "Luck", None))
        self.lineEditRHStr.setText(_translate("MainWindow", "0", None))
        self.label_56.setText(_translate("MainWindow", "Move", None))
        self.label_57.setText(_translate("MainWindow", "Str", None))
        self.lineRORHSpr.setText(_translate("MainWindow", "0", None))
        self.label_58.setText(_translate("MainWindow", "Body", None))
        self.lineRORHLuck.setText(_translate("MainWindow", "0", None))
        self.label_59.setText(_translate("MainWindow", "Spr", None))
        self.label_60.setText(_translate("MainWindow", "Int", None))
        self.lineRORHLeap.setText(_translate("MainWindow", "0", None))
        self.lineEditRHDex.setText(_translate("MainWindow", "0", None))
        self.label_61.setText(_translate("MainWindow", "Leap", None))
        self.lineRORHRun.setText(_translate("MainWindow", "0", None))
        self.label_62.setText(_translate("MainWindow", "Hits", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Key Skills", None))
        self.label_9.setText(_translate("MainWindow", "Key Skills", None))
        self.label_10.setText(_translate("MainWindow", "LVL", None))
        self.label_11.setText(_translate("MainWindow", "Key Perks / Talents", None))
        self.label_12.setText(_translate("MainWindow", "LVL", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "GroupBox", None))
        self.label_13.setText(_translate("MainWindow", "Life Path:", None))
        self.label_14.setText(_translate("MainWindow", "Goals:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Right Hand", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Stats", None))
        self.label_86.setText(_translate("MainWindow", "Name:", None))
        self.label_63.setText(_translate("MainWindow", "Run", None))
        self.label_64.setText(_translate("MainWindow", "Stun", None))
        self.lineROLHSwim.setText(_translate("MainWindow", "0", None))
        self.label_65.setText(_translate("MainWindow", "Rec", None))
        self.lineEditLHTech.setText(_translate("MainWindow", "0", None))
        self.lineROLHEnd.setText(_translate("MainWindow", "0", None))
        self.lineROLHStun.setText(_translate("MainWindow", "0", None))
        self.lineEditLHInt.setText(_translate("MainWindow", "0", None))
        self.label_66.setText(_translate("MainWindow", "Dex", None))
        self.label_67.setText(_translate("MainWindow", "End", None))
        self.lineROLHHum.setText(_translate("MainWindow", "0", None))
        self.lineROLHRec.setText(_translate("MainWindow", "0", None))
        self.label_68.setText(_translate("MainWindow", "Cool", None))
        self.lineEditLHCool.setText(_translate("MainWindow", "0", None))
        self.label_69.setText(_translate("MainWindow", "Swim", None))
        self.lineROLHHits.setText(_translate("MainWindow", "0", None))
        self.lineEditLHWill.setText(_translate("MainWindow", "0", None))
        self.lineEditLHMove.setText(_translate("MainWindow", "0", None))
        self.lineEditLHRef.setText(_translate("MainWindow", "0", None))
        self.label_70.setText(_translate("MainWindow", "Ref", None))
        self.label_71.setText(_translate("MainWindow", "Hum", None))
        self.label_72.setText(_translate("MainWindow", "Will", None))
        self.label_73.setText(_translate("MainWindow", "Tech", None))
        self.lineEditLHCon.setText(_translate("MainWindow", "0", None))
        self.label_74.setText(_translate("MainWindow", "Con", None))
        self.lineEditLHBody.setText(_translate("MainWindow", "0", None))
        self.label_75.setText(_translate("MainWindow", "Luck", None))
        self.lineEditLHStr.setText(_translate("MainWindow", "0", None))
        self.label_76.setText(_translate("MainWindow", "Move", None))
        self.label_77.setText(_translate("MainWindow", "Str", None))
        self.lineROLHSpr.setText(_translate("MainWindow", "0", None))
        self.label_78.setText(_translate("MainWindow", "Body", None))
        self.lineROLHLuck.setText(_translate("MainWindow", "0", None))
        self.label_79.setText(_translate("MainWindow", "Spr", None))
        self.label_80.setText(_translate("MainWindow", "Int", None))
        self.lineROLHLeap.setText(_translate("MainWindow", "0", None))
        self.lineEditLHDex.setText(_translate("MainWindow", "0", None))
        self.label_81.setText(_translate("MainWindow", "Leap", None))
        self.lineROLHRun.setText(_translate("MainWindow", "0", None))
        self.label_82.setText(_translate("MainWindow", "Hits", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "Key Skills", None))
        self.label_15.setText(_translate("MainWindow", "Key Skills", None))
        self.label_16.setText(_translate("MainWindow", "LVL", None))
        self.label_17.setText(_translate("MainWindow", "Key Perks / Talents", None))
        self.label_18.setText(_translate("MainWindow", "LVL", None))
        self.groupBox_10.setTitle(_translate("MainWindow", "GroupBox", None))
        self.label_19.setText(_translate("MainWindow", "Life Path:", None))
        self.label_20.setText(_translate("MainWindow", "Goals:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Left Hand", None))
        self.groupBox_11.setTitle(_translate("MainWindow", "Troops:", None))
        self.label_21.setText(_translate("MainWindow", "Leaders:", None))
        self.label_84.setText(_translate("MainWindow", "Soldiers:", None))
        self.label_85.setText(_translate("MainWindow", "Grunts:", None))
        self.groupBox_12.setTitle(_translate("MainWindow", "Assets", None))
        self.groupBox_13.setTitle(_translate("MainWindow", "Vehicles", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Body", None))

