# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'meta_char_window.ui'
#
# Created: Wed Jun  3 00:22:50 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEditName = QtGui.QLineEdit(self.groupBox)
        self.lineEditName.setObjectName(_fromUtf8("lineEditName"))
        self.horizontalLayout_3.addWidget(self.lineEditName)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.plainTextEditHistory = QtGui.QPlainTextEdit(self.groupBox)
        self.plainTextEditHistory.setObjectName(_fromUtf8("plainTextEditHistory"))
        self.horizontalLayout_4.addWidget(self.plainTextEditHistory)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addWidget(self.groupBox)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_23 = QtGui.QLabel(self.groupBox_2)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_2.addWidget(self.label_23, 2, 4, 1, 1)
        self.label_24 = QtGui.QLabel(self.groupBox_2)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_2.addWidget(self.label_24, 2, 9, 1, 1)
        self.lineROSwim = QtGui.QLineEdit(self.groupBox_2)
        self.lineROSwim.setMaxLength(3)
        self.lineROSwim.setReadOnly(True)
        self.lineROSwim.setObjectName(_fromUtf8("lineROSwim"))
        self.gridLayout_2.addWidget(self.lineROSwim, 3, 6, 1, 1)
        self.label_25 = QtGui.QLabel(self.groupBox_2)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_2.addWidget(self.label_25, 2, 2, 1, 1)
        self.lineEditTech = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditTech.setMaxLength(3)
        self.lineEditTech.setObjectName(_fromUtf8("lineEditTech"))
        self.gridLayout_2.addWidget(self.lineEditTech, 1, 2, 1, 1)
        self.lineROEnd = QtGui.QLineEdit(self.groupBox_2)
        self.lineROEnd.setMaxLength(3)
        self.lineROEnd.setReadOnly(True)
        self.lineROEnd.setObjectName(_fromUtf8("lineROEnd"))
        self.gridLayout_2.addWidget(self.lineROEnd, 3, 3, 1, 1)
        self.lineROStun = QtGui.QLineEdit(self.groupBox_2)
        self.lineROStun.setMaxLength(3)
        self.lineROStun.setReadOnly(True)
        self.lineROStun.setObjectName(_fromUtf8("lineROStun"))
        self.gridLayout_2.addWidget(self.lineROStun, 3, 9, 1, 1)
        self.lineEditInt = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditInt.setMaxLength(3)
        self.lineEditInt.setObjectName(_fromUtf8("lineEditInt"))
        self.gridLayout_2.addWidget(self.lineEditInt, 1, 0, 1, 1)
        self.label_26 = QtGui.QLabel(self.groupBox_2)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_2.addWidget(self.label_26, 0, 3, 1, 1)
        self.label_27 = QtGui.QLabel(self.groupBox_2)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_2.addWidget(self.label_27, 2, 3, 1, 1)
        self.lineROHum = QtGui.QLineEdit(self.groupBox_2)
        self.lineROHum.setMaxLength(3)
        self.lineROHum.setReadOnly(True)
        self.lineROHum.setObjectName(_fromUtf8("lineROHum"))
        self.gridLayout_2.addWidget(self.lineROHum, 3, 1, 1, 1)
        self.lineRORec = QtGui.QLineEdit(self.groupBox_2)
        self.lineRORec.setMaxLength(3)
        self.lineRORec.setReadOnly(True)
        self.lineRORec.setObjectName(_fromUtf8("lineRORec"))
        self.gridLayout_2.addWidget(self.lineRORec, 3, 2, 1, 1)
        self.label_28 = QtGui.QLabel(self.groupBox_2)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_2.addWidget(self.label_28, 0, 4, 1, 1)
        self.lineEditCool = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditCool.setMaxLength(3)
        self.lineEditCool.setObjectName(_fromUtf8("lineEditCool"))
        self.gridLayout_2.addWidget(self.lineEditCool, 1, 4, 1, 1)
        self.label_29 = QtGui.QLabel(self.groupBox_2)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_2.addWidget(self.label_29, 2, 6, 1, 1)
        self.lineROHits = QtGui.QLineEdit(self.groupBox_2)
        self.lineROHits.setMaxLength(3)
        self.lineROHits.setReadOnly(True)
        self.lineROHits.setObjectName(_fromUtf8("lineROHits"))
        self.gridLayout_2.addWidget(self.lineROHits, 3, 8, 1, 1)
        self.lineEditWill = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditWill.setMaxLength(3)
        self.lineEditWill.setObjectName(_fromUtf8("lineEditWill"))
        self.gridLayout_2.addWidget(self.lineEditWill, 1, 5, 1, 1)
        self.lineEditMove = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditMove.setMaxLength(3)
        self.lineEditMove.setObjectName(_fromUtf8("lineEditMove"))
        self.gridLayout_2.addWidget(self.lineEditMove, 1, 8, 1, 1)
        self.lineEditRef = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditRef.setMaxLength(3)
        self.lineEditRef.setObjectName(_fromUtf8("lineEditRef"))
        self.gridLayout_2.addWidget(self.lineEditRef, 1, 1, 1, 1)
        self.label_30 = QtGui.QLabel(self.groupBox_2)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_2.addWidget(self.label_30, 0, 1, 1, 1)
        self.label_31 = QtGui.QLabel(self.groupBox_2)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_2.addWidget(self.label_31, 2, 1, 1, 1)
        self.label_32 = QtGui.QLabel(self.groupBox_2)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_2.addWidget(self.label_32, 0, 5, 1, 1)
        self.label_33 = QtGui.QLabel(self.groupBox_2)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_2.addWidget(self.label_33, 0, 2, 1, 1)
        self.lineEditCon = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditCon.setMaxLength(3)
        self.lineEditCon.setObjectName(_fromUtf8("lineEditCon"))
        self.gridLayout_2.addWidget(self.lineEditCon, 1, 7, 1, 1)
        self.label_34 = QtGui.QLabel(self.groupBox_2)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_2.addWidget(self.label_34, 0, 7, 1, 1)
        self.lineEditBody = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditBody.setMaxLength(3)
        self.lineEditBody.setObjectName(_fromUtf8("lineEditBody"))
        self.gridLayout_2.addWidget(self.lineEditBody, 1, 9, 1, 1)
        self.label_35 = QtGui.QLabel(self.groupBox_2)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_2.addWidget(self.label_35, 2, 0, 1, 1)
        self.lineEditStr = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditStr.setMaxLength(3)
        self.lineEditStr.setObjectName(_fromUtf8("lineEditStr"))
        self.gridLayout_2.addWidget(self.lineEditStr, 1, 6, 1, 1)
        self.label_36 = QtGui.QLabel(self.groupBox_2)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_2.addWidget(self.label_36, 0, 8, 1, 1)
        self.label_37 = QtGui.QLabel(self.groupBox_2)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_2.addWidget(self.label_37, 0, 6, 1, 1)
        self.lineROSpr = QtGui.QLineEdit(self.groupBox_2)
        self.lineROSpr.setMaxLength(3)
        self.lineROSpr.setReadOnly(True)
        self.lineROSpr.setObjectName(_fromUtf8("lineROSpr"))
        self.gridLayout_2.addWidget(self.lineROSpr, 3, 5, 1, 1)
        self.label_38 = QtGui.QLabel(self.groupBox_2)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_2.addWidget(self.label_38, 0, 9, 1, 1)
        self.lineROLuck = QtGui.QLineEdit(self.groupBox_2)
        self.lineROLuck.setMaxLength(3)
        self.lineROLuck.setReadOnly(True)
        self.lineROLuck.setObjectName(_fromUtf8("lineROLuck"))
        self.gridLayout_2.addWidget(self.lineROLuck, 3, 0, 1, 1)
        self.label_39 = QtGui.QLabel(self.groupBox_2)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_2.addWidget(self.label_39, 2, 5, 1, 1)
        self.label_40 = QtGui.QLabel(self.groupBox_2)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_2.addWidget(self.label_40, 0, 0, 1, 1)
        self.lineROLeap = QtGui.QLineEdit(self.groupBox_2)
        self.lineROLeap.setMaxLength(3)
        self.lineROLeap.setReadOnly(True)
        self.lineROLeap.setObjectName(_fromUtf8("lineROLeap"))
        self.gridLayout_2.addWidget(self.lineROLeap, 3, 7, 1, 1)
        self.lineEditDex = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditDex.setMaxLength(3)
        self.lineEditDex.setObjectName(_fromUtf8("lineEditDex"))
        self.gridLayout_2.addWidget(self.lineEditDex, 1, 3, 1, 1)
        self.label_41 = QtGui.QLabel(self.groupBox_2)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_2.addWidget(self.label_41, 2, 7, 1, 1)
        self.lineRORun = QtGui.QLineEdit(self.groupBox_2)
        self.lineRORun.setMaxLength(3)
        self.lineRORun.setReadOnly(True)
        self.lineRORun.setObjectName(_fromUtf8("lineRORun"))
        self.gridLayout_2.addWidget(self.lineRORun, 3, 4, 1, 1)
        self.label_42 = QtGui.QLabel(self.groupBox_2)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_2.addWidget(self.label_42, 2, 8, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MetaChar Creator", None))
        self.groupBox.setTitle(_translate("MainWindow", "Meta Char", None))
        self.label.setText(_translate("MainWindow", "Name:", None))
        self.label_2.setText(_translate("MainWindow", "History:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Main", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox", None))
        self.label_23.setText(_translate("MainWindow", "Run", None))
        self.label_24.setText(_translate("MainWindow", "Stun", None))
        self.lineROSwim.setText(_translate("MainWindow", "0", None))
        self.label_25.setText(_translate("MainWindow", "Rec", None))
        self.lineEditTech.setText(_translate("MainWindow", "0", None))
        self.lineROEnd.setText(_translate("MainWindow", "0", None))
        self.lineROStun.setText(_translate("MainWindow", "0", None))
        self.lineEditInt.setText(_translate("MainWindow", "0", None))
        self.label_26.setText(_translate("MainWindow", "Dex", None))
        self.label_27.setText(_translate("MainWindow", "End", None))
        self.lineROHum.setText(_translate("MainWindow", "0", None))
        self.lineRORec.setText(_translate("MainWindow", "0", None))
        self.label_28.setText(_translate("MainWindow", "Cool", None))
        self.lineEditCool.setText(_translate("MainWindow", "0", None))
        self.label_29.setText(_translate("MainWindow", "Swim", None))
        self.lineROHits.setText(_translate("MainWindow", "0", None))
        self.lineEditWill.setText(_translate("MainWindow", "0", None))
        self.lineEditMove.setText(_translate("MainWindow", "0", None))
        self.lineEditRef.setText(_translate("MainWindow", "0", None))
        self.label_30.setText(_translate("MainWindow", "Ref", None))
        self.label_31.setText(_translate("MainWindow", "Hum", None))
        self.label_32.setText(_translate("MainWindow", "Will", None))
        self.label_33.setText(_translate("MainWindow", "Tech", None))
        self.lineEditCon.setText(_translate("MainWindow", "0", None))
        self.label_34.setText(_translate("MainWindow", "Con", None))
        self.lineEditBody.setText(_translate("MainWindow", "0", None))
        self.label_35.setText(_translate("MainWindow", "Luck", None))
        self.lineEditStr.setText(_translate("MainWindow", "0", None))
        self.label_36.setText(_translate("MainWindow", "Move", None))
        self.label_37.setText(_translate("MainWindow", "Str", None))
        self.lineROSpr.setText(_translate("MainWindow", "0", None))
        self.label_38.setText(_translate("MainWindow", "Body", None))
        self.lineROLuck.setText(_translate("MainWindow", "0", None))
        self.label_39.setText(_translate("MainWindow", "Spr", None))
        self.label_40.setText(_translate("MainWindow", "Int", None))
        self.lineROLeap.setText(_translate("MainWindow", "0", None))
        self.lineEditDex.setText(_translate("MainWindow", "0", None))
        self.label_41.setText(_translate("MainWindow", "Leap", None))
        self.lineRORun.setText(_translate("MainWindow", "0", None))
        self.label_42.setText(_translate("MainWindow", "Hits", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Brain", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Right Hand", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Left Hand", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Body", None))

